### ISSUE TITLE
Could not load RNOneSignal native module. Make sure native dependencies are properly linked.

### ISSUE THREAD

**Issue by rubendmatos1985** [OneSignal/onesignal-expo-plugin#100]
I am receiving this error.

![image](https://user-images.githubusercontent.com/23451812/178159212-691aa960-44a5-440d-ba2a-7808dd30ba5f.png)

The dependencies installed on my project:
![image](https://user-images.githubusercontent.com/23451812/178159226-7e853e58-8e89-43c4-b1e2-531a6c4b661e.png)

### OneSignal Expo SDK version

1.0.2

### Platform

Android

### Relevant log output

```Shell
Could not load RNOneSignal native module. Make sure native dependencies are properly linked.
at node_modules\expo\build\environment\react-native-logs.fx.js:27:4 in error
at node_modules\react-native-onesignal\dist\helpers.js:15:8 in isNativeModuleLoaded
at node_modules\react-native-onesignal\dist\index.js:61:13 in OneSignal.setAppId
at App.tsx:15:0 in <global>
at node_modules\metro-runtime\src\polyfills\require.js:339:11 in loadModuleImplementation
at index.js:3:0 in <global>
at node_modules\metro-runtime\src\polyfills\require.js:339:11 in loadModuleImplementation
at node_modules\metro-runtime\src\polyfills\require.js:200:44 in guardedLoadModule
at http://192.168.2.130:19000/index.bundle?platform=android&dev=true&hot=false&strict=false&minify=false:230494:3 in global code
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rubendmatos1985** [comment]
Hi. Yes indeed the problem was that i was running the app on expo go. Now on a physical device is running without errors. Thanks for the hint.

**Comment by rgomezp** [comment]
My pleasure.
