### ISSUE TITLE
After installing, getting Plugin is an expected type: object error

### ISSUE THREAD

**Issue by pratikdhody** [OneSignal/onesignal-expo-plugin#102]
### How can we help?

Please advise how to install to React Native Expo project.

### OneSignal Expo SDK version

1.0.2

### Platform

iOS, Android

### Relevant log output

```Shell
Plugin is an unexpected type: object
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pratikdhody** [comment]
had wrong config in app.json - ignore me.

**Comment by BioKobena** [comment]
Please, how to resolve this wrong ?

**Comment by jailsonmartinsfilho** [comment]
> Please, how to resolve this wrong ?

Brackets inside plugins are probably missing, everything involved in plugins should be in brackets like this, for example:

"plugins": [
      [
          "expo-font",
        {
          "fonts": ["./assets/Araboto.ttf"]
        }
      ]
    ]

**Comment by jailsonmartinsfilho** [comment]
Brackets inside plugins are probably missing, everything involved in plugins should be in double brackets like this, for example:

```
"plugins": [
      [
          "expo-font",
        {
          "fonts": ["./assets/Araboto.ttf"]
        }
      ]
    ]
```
