### ISSUE TITLE
[Bug]: EAS Capability Sync removing iOS app groups entitlement from bundle identifier

### ISSUE THREAD

**Issue by jesse-savary** [OneSignal/onesignal-expo-plugin#103]
### What happened?

Hello,

Something appears to be up with EAS removing the correct entitlements/capabilities from my bundle identifier. This results in an invalid provisioning profile being generated which causes our build to fail.

I am able to work around the issue by manually updating the OneSignal bundle identifier inside the Apple Developer Portal, then prefixing my build command with `EXPO_NO_CAPABILITY_SYNC=1` (see https://docs.expo.dev/build-reference/ios-capabilities/#debugging for details).

### Steps to reproduce?

```Markdown
1. Create a bare workflow app
2. Add onesignal-expo-plugin
3. Run `eas build --local --platform ios`
```

### What did you expect to happen?

I expected the OneSignal plugin to generate whatever is needed so that Expo adds entitlements to the identifiers instead of removing them.

### OneSignal Expo SDK version

Latest commits from Git

### Platform

iOS

### Relevant log output

```Shell
Output of `eas build --profile production --local --platform ios`

...

Setting up credentials for target OneSignalNotificationServiceExtension (com.lckroom.apps.lckroom-client.OneSignalNotificationServiceExtension)

✔ Bundle identifier registered com.lckroom.apps.lckroom-client.OneSignalNotificationServiceExtension
✔ Synced capabilities: Disabled: App Groups <----- this line
✔ Synced capability identifiers: No updates
✔ Fetched Apple distribution certificates
✔ Fetched Apple provisioning profiles
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rgomezp** [comment]
@jesse-savary ,
Howdy, can you please also specify the `react-native-onesignal` version that you are using?

**Comment by rgomezp** [comment]
Closing due to no response

**Comment by AdamDiament** [comment]
@jesse-savary I have the same issue. Did you find a workaround?
