### ISSUE TITLE
ERROR  Could not load RNOneSignal native module. Make sure native dependencies are properly linked.

### ISSUE THREAD

**Issue by Umark3434** [OneSignal/onesignal-expo-plugin#112]
I am attempting to set up OneSignal on my React-Native application. I have followed the steps [here](https://onesignal.com/blog/how-to-add-android-push-notifications-to-your-react-native-expo-app) precisely.

My question is: If I am using an Android Emulator (and I understand that the push notifications will not work), is this the cause of the error? Or is this error unrelated to using the emulator with push notifications?

And if it is unrelated, what can I do to fix this issue?

### OneSignal Expo SDK version

1.1.0

### Platform

Android

### Relevant log output

```Shell
Could not load RNOneSignal native module. Make sure native dependencies are properly linked.
at node_modules/react-native-onesignal/dist/helpers.js:15:8 in isNativeModuleLoaded
at node_modules/react-native-onesignal/dist/index.js:61:13 in OneSignal.setAppId
at App.js:7:2 in App
at node_modules/react-native/Libraries/ReactNative/renderApplication.js:80:4 in renderApplication
at node_modules/react-native/Libraries/ReactNative/AppRegistry.js:119:25 in runnables.appKey.run
at node_modules/react-native/Libraries/ReactNative/AppRegistry.js:213:4 in runApplication
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alicanso** [comment]
same here

**Comment by brismithers** [comment]
Hi @Umark3434, can you confirm which environment you are starting your application? As a reminder, these are the supported environments.

[The Expo run commands](https://docs.expo.dev/workflow/customizing/) (expo run:[android|ios])
[Custom clients](https://blog.expo.dev/introducing-custom-development-clients-5a2c79a9ddf8)
[EAS Build](https://docs.expo.dev/build/introduction/)

Please make sure you are building and running in one of them. The Expo Go app is **not** a supported environment.

Thanks!

**Comment by Umark3434** [comment]
Yeah, I understand later. I was trying to run with Expo Go.
If I do not run these commands: **expo prebuild** and **expo run:android**.  If I directly generate apk (expo build:android) and run it on the real device will it work?

>
