### ISSUE TITLE
Can i skip the creation of iOS App Group ID PACKAGENAME.onesignal?

### ISSUE THREAD

**Issue by dcesca** [OneSignal/onesignal-expo-plugin#113]
Hi,
is there a way to skip the creation of the .onesignal AppGroup ID PACKAGENAME.onesignal?
The group is already present but is linked to the previus developer account who published the app and then transferred the app to my client’s Apple Developer Account.
Problem 1: the group ids are not transferred so the creation of the AppGroupId fails and the build cannot be created.
Problem 2: the developer account the app group id is linked to is not active anymore

Any idea?

P.s. I already wrote a message to Apple asking if they could remove the app group id, waiting for a response

**Comment by brismithers** [comment]
Hi @dcesca there is no current way to bypass this phase of the plugin without modifying the plugin (I think by removing this line [here](https://github.com/OneSignal/onesignal-expo-plugin/blob/main/onesignal/withOneSignalIos.ts#L137)).

That said though I'm not sure if it will work.  If the entitlements plist doesn't have this entitlement the build will go through but it will no longer have the appropriate AppGroup?

Let me know your thoughts, thanks!

**Comment by dcesca** [comment]
Hi @brismithers actually I think that the entitlement shoud be included in plist the only thing blocking the build is the fact that “somenthing” tries to create the appgroup in the apple developer account … and failing because it tries to create somenthing already present with the same name somewhere in the Apple archives.
Anyway let’s wait Apple answer hoping they’ll remove the “ghost app group” from the other (now disabled/removed) apple account who created the app group in the first place.

**Comment by brismithers** [comment]
Hi @dcesca were you able to get a response from Apple on this?

**Comment by dcesca** [comment]
@brismithers it’s actually the longest procedure ever. Apple says that they need to have a contact with the previous developer to confirm he agrees to the deletion of the group id… I had several calls and emails with them and now they and this is what they came up with. Simply unbelivable, the app was transfered to is by this dev so this is not enough for them to proceed. Let’s wait their chat with the dev and let’s hope they’ll be ok on deleting this group id

**Comment by dcesca** [comment]
@brismithers hi, behold ladies and gentlemen Apple deleted the app group id.
If you find yourself in this situation you want to do this:
- contact apple by phone if available, using the contact form https://developer.apple.com/it/support/
- explain you need to delete the app group id owned by one of the previous developers who published the app and transferred the app to your account. The app group is not transferred along
- put the email of the previous account in the message with his name and surname
- explain why the previous developer can’t access his account or can’t access the app group id list (i.e. He’scnot paying the subscription)
- Wait their reply, they’ll ask you to forward the email containing a link to contact the apple developer supportto the previus developer
- Ask the previous developer to comply and write the message using his account
- pray… a lot
- Hopefully Apple will delete the app group id
Thanks to the Italian Apple Supervisors!
