### ISSUE TITLE
[question]: 

### ISSUE THREAD

**Issue by poinch** [OneSignal/onesignal-expo-plugin#117]
### How can we help?

I couldn't build anymore for android, the build failed because i have to downgrade the resolution strategy with this code:

```
import { withAppBuildGradle } from "@expo/config-plugins";

const newResolutionStrategyGradle = `
configurations.all {
    resolutionStrategy {
        force 'androidx.work:work-runtime:2.6.0'
    }
}`;

const withWorkingWorkRuntimeVersion = (config) => {
  return withAppBuildGradle(config, (newConfig) => {
    newConfig.modResults.contents = `${newResolutionStrategyGradle.trimStart()}\n\n${newConfig.modResults.contents}`;
    return newConfig;
  });
};

module.exports = ({ config }) => {
  return withWorkingWorkRuntimeVersion(config);
};
```

Now this problem is fixed but i get this annoying log "onesignal-expo-plugin: No specific actions required for OneSignal on Android..." every couple of seconds, why? How can i fix it? It's my approach to downgrade the resolution strategy correct?

### OneSignal Expo SDK version

1.1.0

### Platform

Android

### Relevant log output

```Shell
onesignal-expo-plugin: No specific actions required for OneSignal on Android...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brismithers** [comment]
Hi @poinch upgrading to the newest release (v1.1.1), you will no longer see those messages produced by the plugin.
