### ISSUE TITLE
[question]: Apn push notifications key instead of certificates

### ISSUE THREAD

**Issue by jurica-penjgusic** [OneSignal/onesignal-expo-plugin#119]
### How can we help?

Is there any plans to support APN push notifications key that don’t expire instead of existing push notifications certificates.

### OneSignal Expo SDK version

*

### Platform

iOS

### Relevant log output

```Shell
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jmadler** [comment]
Hi!  Yes, we do plan to support Apple's Token-Based Authentication scheme, but at the moment, we only support the Certificate-based scheme.  Keep an eye out for the feature announcement in our usual email newsletters.
