### ISSUE TITLE
[Bug]: Push works in dev but when generating the apk the device is not registered in the onesignal dashboard (push does not work)

### ISSUE THREAD

**Issue by GleidsonDaniel** [OneSignal/onesignal-expo-plugin#121]
### What happened?

Push works in dev but when generating the apk the device is not registered in the onesignal dashboard (push does not work)
I followed the sample documentation in this repo here: https://github.com/OneSignalDevelopers/OneSignal-ReactNative-Expo-Sample

### Steps to reproduce?

```Markdown
Create an expo project.
Run expo prebuild.
Generate an apk.
```

### What did you expect to happen?

The pushs working on dev and prod.

### OneSignal Expo SDK version

"react-native-onesignal": "^4.4.1"
"onesignal-expo-plugin": "^1.1.0"

"expo": "~45.0.0"

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brismithers** [comment]
Hi @GleidsonDaniel, can you please provide the version and device you are running the prod apk under?  Is it the same as your dev?  Thanks!

**Comment by GleidsonDaniel** [comment]
Yes is the same app and same device.
In dev runs ok.
After generate apk, dont work.
Xiaomi MI 11i - Android 12

**Comment by GleidsonDaniel** [comment]
Generating local push works, using EAS doesn't.
It must be some incompatibility with the EAS.

**Comment by brismithers** [comment]
@GleidsonDaniel unfortunately I'm unable to reproduce what you're seeing.  I was able to generate an APK through an EAS build to generate an APK, OneSignal registration and push notifications are working as expected. Can you show me your `eas.json` file for the profile you are using to run the build, as well as the command you use to kick off the build?  Thanks so much!

**Comment by mak12** [comment]
hi @brismithers 

```
{
  "cli": {
    "version": ">= 3.8.1"
  },
  "build": {
    "development": {
      "developmentClient": true,
      "distribution": "internal",
      "ios": {
        "resourceClass": "m-medium"
      }
    },
    "preview": {
      "distribution": "internal"
    },
    "production": {
      "ios": {
        "resourceClass": "m-medium"
      }
    }
  },
  "submit": {
    "production": {}
  }
}

```
This is my eas file, I am having the same problem
