### ISSUE TITLE
[Bug]: External User Id is not being set in production

### ISSUE THREAD

**Issue by jorgeruvalcaba** [OneSignal/onesignal-expo-plugin#123]
### What happened?

I'm setting an external user id as mentioned in the docs, but it's not being reflected in the dashboard for the production build.

This is my `app.json` config:

```json
"plugins": [
      [
        "onesignal-expo-plugin",
        {
          "mode": "production",
          "devTeam": "ABC1234"
        }
      ],
      "sentry-expo",
      ...
]
```

And this is how I'm using the method:

```ts
export const initOneSignal = (userId: string) => {
  if (!shouldRunNativeDeps || !oneSignalAppId) return

  OneSignal.setAppId(oneSignalAppId)
  OneSignal.setLogLevel(6, 0)
  OneSignal.setExternalUserId(userId)

  OneSignal.setNotificationWillShowInForegroundHandler(
    (notificationReceivedEvent) => {
      const notification = notificationReceivedEvent.getNotification()
      // Complete with null means don't show a notification.
      notificationReceivedEvent.complete(notification)
    },
  )
}
```

Not sure if I need to call `setExternalUserId` method in a different order or out of `initOneSignal` but it only doesn't work in production env. Notifications are being subscribed properly.

### Development
![Screen Shot 2022-09-19 at 1 06 04 p m](https://user-images.githubusercontent.com/7416811/191089898-54a80a1b-bc77-44e1-9d4c-22956b9742a3.png)

### Production
![Screen Shot 2022-09-19 at 1 32 19 p m](https://user-images.githubusercontent.com/7416811/191090007-37c3e068-9ade-45d7-a7df-78d232c31877.png)

### Steps to reproduce?

```Markdown
1. Start the app.
2. Accept the permission in the push notification prompt.
3. See the device in the dashboard.
```

### What did you expect to happen?

Get external user id set as with other environments.

### OneSignal Expo SDK version

1.0.2

### Platform

iOS, Android

### Relevant log output

```Shell
Nothing relevant to show.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brismithers** [comment]
@jorgeruvalcaba how you have it looks correct to me, can you provide the device logs from the production deployment?  Also can you confirm if this is happening on Android, iOS, or both? Thanks!

**Comment by jorgeruvalcaba** [comment]
> @jorgeruvalcaba how you have it looks correct to me, can you provide the device logs from the production deployment? Also can you confirm if this is happening on Android, iOS, or both? Thanks!

Thanks for the quick response @brismithers, here are the [logs](https://github.com/OneSignal/onesignal-expo-plugin/files/9601819/xcode-build-47443f73-ef77-4e70-b276-f58f5677b7c6.log). This is happening on both platforms.

**Comment by brismithers** [comment]
apologies @jorgeruvalcaba this looks like the build logs.  I was hoping to get a hold of the the device logs showing the app being initialized, calls to setExternalUserId, etc.  If you could provide those that would be great!

**Comment by jorgeruvalcaba** [comment]
@brismithers here are the correct [device logs](https://github.com/OneSignal/onesignal-expo-plugin/files/9622005/iPhone.Jorge.log)

Let me know if more information is needed from my side.

**Comment by brismithers** [comment]
@jorgeruvalcaba looks like that log isn't showing the time period where you are setting the external ID. Could you provide the device logs that show when you are initializing the OneSignal SDK and setting the external ID?   Usually this occurs when starting up the application.  Thanks!

**Comment by jorgeruvalcaba** [comment]
@brismithers here are the correct [logs](https://github.com/OneSignal/onesignal-expo-plugin/files/9637945/iPhone.Jorge.log), there are some `OneSignalCore` logs but not I'm not seeing any related with setting the external ID.

**Comment by brismithers** [comment]
@jorgeruvalcaba those logs also look like they aren't showing the initialization of the app.  With VERBOSE logging (which looks to be set correctly), I should see these these 2 statements at a minimum as part of the OneSignal SDK initialization process for iOS:

`setLaunchOptions() called with launchOptions: XXXX`

`setAppId(id) called with appId: XXXX`

Can you try to find the logs around this time period? Thanks!
