### ISSUE TITLE
[Bug]: Invariant Violation: "main" has not been registered.

### ISSUE THREAD

**Issue by suetter** [OneSignal/onesignal-expo-plugin#125]
### What happened?

Hi there,
i'm facing the following ploblem :

`Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:4 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError`

my local dev server works fine, i think the problem is that the plugin cannot be loaded correctly.

dependencies : 
`
"dependencies": {
    "@gorhom/bottom-sheet": "^4.4.3",
    "@react-native-community/checkbox": "^0.5.12",
    "@react-native-community/slider": "4.2.1",
    "@react-navigation/drawer": "^6.4.3",
    "@react-navigation/elements": "^1.3.4",
    "@react-navigation/native": "^6.0.11",
    "@react-navigation/native-stack": "^6.7.0",
    "@rneui/base": "^4.0.0-rc.5",
    "@rneui/themed": "^4.0.0-rc.5",
    "expo": "~45.0.0",
    "expo-av": "~11.2.3",
    "expo-font": "~10.1.0",
    "expo-screen-orientation": "~4.2.0",
    "expo-splash-screen": "~0.15.1",
    "expo-status-bar": "~1.3.0",
    "expo-updates": "~0.13.4",
    "expo-video-player": "^2.1.0",
    "firebase": "9.6.11",
    "onesignal-expo-plugin": "^1.1.1",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-native": "0.68.2",
    "react-native-gesture-handler": "^2.2.1",
    "react-native-ionicons": "^4.6.5",
    "react-native-onesignal": "^4.4.1",
    "react-native-reanimated": "^2.8.0",
    "react-native-safe-area-context": "4.2.4",
    "react-native-screens": "~3.11.1",
    "react-native-slider": "^0.11.0",
    "react-native-vector-icons": "^9.2.0",
    "react-native-web": "0.17.7"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9"
  }
`

### Steps to reproduce?

```Markdown
i'm facing the same problem with this this example : 
https://github.com/OneSignalDevelopers/OneSignal-ReactNative-Expo-Sample

steps :
cloning the project
run npm install
run expo start -c
using Expo go app to run the project
after the javascript building, the application crashes and the terminal show the error above
```

### What did you expect to happen?

run the project without problems

### OneSignal Expo SDK version

4.4.1

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by brismithers** [comment]
Hi @suetter, the Expo Go app is unfortunately **not** a supported environment due to OneSignal depending on a native module.  Please make sure you are building and running in one of the supported environments: 

[The Expo run commands](https://docs.expo.dev/workflow/customizing/) (expo run:[android|ios])
[Custom clients](https://blog.expo.dev/introducing-custom-development-clients-5a2c79a9ddf8)
[EAS Build](https://docs.expo.dev/build/introduction/)

Thanks!
