### ISSUE TITLE
[Bug]: Android build failing when on Expo SDK 44

### ISSUE THREAD

**Issue by lindanip** [OneSignal/onesignal-expo-plugin#132]
### What happened?

Hey

I get this error when I build for Android, 
this error occurs under the `run gradlew` after the `configure expo-updates`,
when building using `eas build`

`[stderr] FAILURE: Build failed with an exception.
[stderr] * What went wrong:
[stderr] Execution failed for task ':app:checkReleaseAarMetadata'.
[stderr] > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
[stderr]    > The minCompileSdk (31) specified in a
[stderr]      dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
[stderr]      is greater than this module's compileSdkVersion (android-30).
[stderr]      Dependency: androidx.work:work-runtime:2.7.1.
[stderr]      AAR metadata file: /home/expo/.gradle/caches/transforms-3/c9b633a7cdef94f5ad87c49ed563a3db/transformed/work-runtime-2.7.1/META-INF/com/android/build/gradle/aar-metadata.properties.
[stderr] * Try:`

 It works fine when I build for iOS, and Im even able to test notifications with internal builds.

Im using:

EXPO SDK 44
React 17.0.1
React Native 0.64.3
onesignal-expo-plugin ^1.1.2
react-native-onesignal ^4.4.1

I am builing using eas build

### Steps to reproduce?

```Markdown
eas build --platform android --profile staging
```

### What did you expect to happen?

expecting and installable apk file after the build completes

### OneSignal Expo SDK version

EXPO SDK 44
React 17.0.1
React Native 0.64.3
onesignal-expo-plugin ^1.1.2
react-native-onesignal ^4.4.1

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brismithers** [comment]
@lindanip thanks for reporting!

The Expo SDK 44 will generate a `build.gradle` file for your app with a `compileSdkVersion` of `30`. However the `react-native-onesignal@4.4.1` depends on library `androidx.work:work-runtime@2.7.1` which requires a minimum compile version of `31`.  I believe the error message is showing this incompatibility.

[Expo SDK 45](https://github.com/expo/expo/blob/main/CHANGELOG.md#4500--2022-04-25) bumped the `compileSdkVersion` from `30` to `31`, are you able to update to either Expo SDK 45 or 46?

**Comment by lindanip** [comment]
Okay I will try upgrading to sdk 45 or 46, thank you very much.
