### ISSUE TITLE
[Bug]: AssertionError [ERR_ASSERTION]: Missing 'ios.bundleIdentifier' in app config.

### ISSUE THREAD

**Issue by yeongchan1228** [OneSignal/onesignal-expo-plugin#139]
### What happened?

Run the expo install onesignal-expo-plugin command
{
"plugins": [
[
"onesignal-expo-plugin",
{
"mode": "development",
}
]
]
}
If you enter the contents in the app.js file and enter the expo start command, Assertion Error [ERR_ASSERTION]: Missing 'ios.bundleIdentifier' in app config.

### Steps to reproduce?

```Markdown
1. expo install onesignal-expo-plugin command
2. Enter content in app.js
3. expo start
```

### What did you expect to happen?

It was expected that the build would succeed and run normally.

### OneSignal Expo SDK version

"expo": "~47.0.3"
"onesignal-expo-plugin": "^1.2.0",

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brismithers** [comment]
Hi @yeongchan1228 thank you for reporting!  I have confirmed this iOS-specific error message does happen even when you intend to run on Android.  To my knowledge there isn't a way to specify you only want a single platform's config changes to be applied, the plugin will always apply to both iOS and Android.

On the iOS side we require `ios.bundleIdentifier` to be specified as we use it to modify the config to include the [Notification Service Extension](https://github.com/OneSignal/onesignal-expo-plugin/blob/main/support/eas/getEasManagedCredentialsConfigExtra.ts).

In your `app.json` file you will need to specify the bundle identifier:

```
    "ios": {
      "supportsTablet": true,
      "buildNumber": "<your_build_number_here>",
      "bundleIdentifier": "<your_bundle_identifier_here>"
    },
```

If you don't intend to ever deploy to iOS, you can provide any non-empty string to the `bundleIdentifier`, the Android builds will work!

I've noted our [README](https://github.com/OneSignal/onesignal-expo-plugin/blob/main/README.md) does *not* include this information. I will leave this issue opened until we can get the README updated to indicate `ios.bundleIdentifier` is also required to exist.  Thanks!

**Comment by RizwansAccount** [comment]
![Screenshot_1](https://github.com/OneSignal/onesignal-expo-plugin/assets/101934259/a307bb82-4914-41e9-9a5d-7659aaee482c)
in app.json file add bundleidentifier in ios
