### ISSUE TITLE
Native module cannot be null

### ISSUE THREAD

**Issue by dcesca** [OneSignal/onesignal-expo-plugin#14]
Hi, after adding

import Constants from "expo-constants";
OneSignal.setAppId(Constants.manifest.extra.oneSignalAppId);

...running the app with expo start keeps giving me "OneSignal is not defined"

Is there something else to import?

Thanks

**Comment by dcesca** [comment]
Hi, I think I found the missing peace: https://docs.expo.dev/clients/getting-started/

Sorry for bothering you, but I think adding this link to your Readme will help a lot, have a nice one

**Comment by rgomezp** [comment]
Thanks for your input @dcesca 

You can see we have included an example project now: https://github.com/OneSignal/onesignal-expo-plugin/tree/main/examples/RNOneSignalExpoExample

Enjoy!
