### ISSUE TITLE
[question]: Using with `sentry-expo` causes entitlements to not be applied correctly on iOS.

### ISSUE THREAD

**Issue by AlexCatch** [OneSignal/onesignal-expo-plugin#144]
### How can we help?

I'm having a weird issue using this plugin in conjunction with the `sentry-expo` plugin. The app's entitlements seem to not be applied correctly.

With the following plugins property:

```
plugins: [
  [
    'onesignal-expo-plugin',
    {
      mode: 'production',
    },
  ],
  'sentry-expo',
]
```
building on EAS, then pulling the entitlements from the app with `codesign -d --entitlements :- ./Payload/APP.app` returns  the following:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "https://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>application-identifier</key>
		<string>C29TM6NW95.com.resorthoppa.hoppa.dev</string>
		<key>com.apple.developer.team-identifier</key>
		<string>C29TM6NW95</string>
		<key>get-task-allow</key>
		<false/>
	</dict>
</plist>
```

with the following plugins property:

```
plugins: [
  [
    'onesignal-expo-plugin',
    {
      mode: 'production',
    },
  ]
]
```

running the same `codesign` command returns

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "https://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>application-identifier</key>
		<string>C29TM6NW95.com.resorthoppa.hoppa.dev</string>
		<key>aps-environment</key>
		<string>production</string>
		<key>com.apple.developer.team-identifier</key>
		<string>C29TM6NW95</string>
		<key>com.apple.security.application-groups</key>
		<array>
			<string>group.com.resorthoppa.hoppa.dev.onesignal</string>
		</array>
		<key>get-task-allow</key>
		<false/>
	</dict>
</plist>
```

Any idea what could be causing this?

### OneSignal Expo SDK version

"onesignal-expo-plugin": "^1.2.0"
"react-native-onesignal": "^4.4.1"

### Platform

iOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rgomezp** [comment]
Howdy,
From what I can tell, none of your previous entitlements are removed, namely team identifier, get-task-allow, and app id. 

This config plugin needs to set some new entitlements like app groups and aps-environment which is what it is doing.

**Comment by AlexCatch** [comment]
Hey,

Sorry, I think I've worded things slightly wrong - it seems like the entitlements are never getting applied.

When the One Signal plugin is the only plugin in the array, the entitlements are correct with `aps-environment` and `com.apple.security.application-groups` both present.

When the one signal plugin is used in conjunction with `sentry-expo`, both `aps-environment` and `com.apple.security.application-groups` are missing from the entitlements.

**Comment by AlexCatch** [comment]
Looking into this more, it seems to work fine if I prebuild the project with `expo prebuild`.

This only occurs when using the fully managed flow.

**Comment by brismithers** [comment]
Hi @AlexCatch sorry I want to make sure I understand.  When you say this only occurs when using the fully managed flow, what command are you using to drive the build?  Are you using something like `eas build --profile development --platform ios`?

**Comment by AlexCatch** [comment]
Sorry for the delayed response - the error seems to have randomly gone away; it was occurring with `eas build` but no longer seems to be the case.

Closing.
