### ISSUE TITLE
[Bug]: "Push Notification" capability not synced with EAS Build for iOS

### ISSUE THREAD

**Issue by dmahajan980** [OneSignal/onesignal-expo-plugin#149]
### What happened?

I have integrated the SDK into my Expo managed workflow app using this config plugin. Whenever I run `eas build ...`, it shows the capabilities enabled for the project. The SDK requires *Push Notification* capability enabled but the terminal does not show the same in the list of capabilities at the beginning of the build:

<img width="580" alt="Screenshot 2022-12-07 at 11 01 03 PM" src="https://user-images.githubusercontent.com/37256767/206255021-51e0e999-cf45-40d4-8028-0298f13ce2de.png">

I have followed the instructions mentioned in [this guide](https://github.com/OneSignal/onesignal-expo-plugin/blob/main/EAS.md).

### Steps to reproduce?

```Markdown
1. Install OneSignal SDK and its config plugin.
2. Add the plugin to `app.json` or `app.config.js`.
3. Configure and run EAS build. Notice the list of **Synced Capabilities**. It does not reflect **Push Notifications** as a capability.
```

### What did you expect to happen?

EAS Build should have shown **Push Notifications** as a capability after adding this config plugin.

### OneSignal Expo SDK version

1.3.0

### Relevant log output

```Shell
✔ Bundle identifier registered com.schmoozeapps.schmooze.staging
✔ Synced capabilities: Enabled: Sign In with Apple
✔ Synced capability identifiers: Linked: group.com.schmoozeapps.schmooze.staging.onesignal
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brismithers** [comment]
Hi @dmahajan980.  Can you tell me what version of `expo` and `expo-cli` you are running?  It will also help if you could provide the output of `expo config --type introspect`. Thanks!

**Comment by ansh** [comment]
I am also facing this issue. 
```
eas-cli/3.1.1 darwin-arm64 node-v16.18.1
expo-cli 6.0.8
expo SDK v47
```
Running expo config gives a lot of sensitive data so I am not comfortable sharing it here. Happy to send it via email! Please let me know where to send it.

**Comment by rgomezp** [comment]
@ansh ,
Please reach out to our support team via Intercom at onesignal.com

**Comment by rgomezp** [comment]
Closing due to no response.
