### ISSUE TITLE
[Bug]: Second extension fails to build – Could not find target

### ISSUE THREAD

**Issue by spoeken** [OneSignal/onesignal-expo-plugin#166]
### What happened?

Hi, I have an app that has an extension to display a home screen widget.
When trying to implement the oneSignal extension the widget fails to build.
As soon as I remove the oneSignal extension everything works as normal. 

The widget is based on this repo: https://github.com/gaishimo/eas-widget-example
Which I believe is inspired by the oneSignal extension. 
I'm suspecting that the workaround used in both extensions is somehow conflicting, but that's just a gut feeling. 

`WORK AROUND for codeProject.addTarget BUG`

### Steps to reproduce?

```Markdown
1. Set up an app with a widget https://github.com/gaishimo/eas-widget-example
2. Implement onesignal-expo-plugin
3. Run `eas build --platform ios --profile preview`
```

### What did you expect to happen?

I expected the app to build without any errors

### OneSignal Expo SDK version

onesignal-expo-plugin: 1.3.1
react-native-onesignal: 4.5.1

### Platform
iOS
### Relevant log output

```Shell
Configuring Xcode project
Assigning provisioning profile '*[expo] com.theappname.app.widget AdHoc XXXXXXX' (Apple Team ID: XXXXXX) to target 'widget'
Could not find target 'widget' in project.pbxproj
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brismithers** [comment]
@spoeken thanks for reporting.  I think I've identified the problem, our approach to modifying the project file isn't consistent with expo's expectations.  The OneSignal plugin (and the widget code) does this:

```
return withXcodeProject(config, async newConfig => {
    const xcodeProject = xcode.project(projPath);
   
   // load the project file ourselves, not received through expo
    xcodeProject.parse(async function(err: Error) {
      // make changes to xcode project file

      // write updated project file ourselves, not returning to expo
      fs.writeFileSync(projPath, xcodeProject.writeSync());
    }
    return newConfig;
  });
```

The concurrent nature of expo plugins means when we read the project file ourselves, it may or may not contain changes made by another plugin.  I believe both the OneSignal plugin and the widget plugin code needs to do something more like this:

```
return withXcodeProject(config, async newConfig => {
      const xcodeProject = newConfig.modResults;
      // make changes to xcode project file passed in via 

     // do NOT save ourselves, expo will do that once all plugins have made their updates.
    }
    return newConfig;
  });
```

Will get this fixed on our side as soon as we can.
