### ISSUE TITLE
[Bug]: I receive notifications in development build, but adhoc/preview/production build not receive notifications and not subscribe

### ISSUE THREAD

**Issue by marcelobarbosaO** [OneSignal/onesignal-expo-plugin#180]
### How can we help?

I created the app using version 1.3.1 of the lib and did all the configuration using the .p8 key. But the skd only subscribes and receives notification in develop/debug. in staging/preview/production mode neither subscribe not receive notification. in plugin configuration i used development for development and production for staging/preview/production

this is my deviceState after allow prompt
![image](https://user-images.githubusercontent.com/9268156/233500935-26817c5f-1704-4ca7-8a7e-0a664161f564.png)

PS: I'm using EAS to generate build, I created all credentials by expo and run locally: expo prebuild and the entitlements are correctly in ios folder, but i have this problem =/
### OneSignal Expo SDK version

1.3.1

### Platform

iOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marcelobarbosaO** [comment]
@brismithers any solution?

**Comment by mmasiulis** [comment]
@marcelobarbosaO I'm experiencing the same issue, any leads how did you solve this?
