### ISSUE TITLE
1.3.2 [Bug]: 'onesignal/onesignal.h' file not found react native

### ISSUE THREAD

**Issue by MortadhaFadhlaoui** [OneSignal/onesignal-expo-plugin#182]
### What happened?

The latest version of the SDK `1.3.2` cause ios build to fail

### Steps to reproduce?

```Markdown
onesignal-expo-plugin@1.3.2
npx expo run:ios
```

### What did you expect to happen?

finish ios build successfully

### OneSignal Expo SDK version

1.3.2

### Platform

iOS

### Relevant log output

```Shell
❌  (ios/OneSignalNotificationServiceExtension/NotificationService.m:1:9)

> 1 | #import <OneSignal/OneSignal.h>
    |         ^ 'OneSignal/OneSignal.h' file not found
  2 | 
  3 | #import "NotificationService.h"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
@MortadhaFadhlaoui Was this working on a previous version and is failing now that you have upgraded? If so which version were you on previously? Has anything else changed in your build process (Mac version, Xcode version, Cocoapods version, etc.)?

**Comment by MortadhaFadhlaoui** [comment]
@emawby nothing has changed so far, I have the same build environment in EAS 
```
Installed software:
- Xcode 14.1 (14B47b)
- Node.js 16.18.1
- Yarn 1.22.17
- pnpm 7.15.0
- npm 8.1.2
- fastlane 2.210.1
- CocoaPods 1.11.3
- Ruby 2.7
- Expo CLI 6.0.0
```
 I only downgrade to 1.3.1 and the build is working again.

**Comment by emawby** [comment]
It looks like the `1.3.2` release only bumped dependency versions and then made [this change](https://github.com/OneSignal/onesignal-expo-plugin/pull/175). That PR is probably causing the issue 👀

**Comment by TNAJanssen** [comment]
Same issue here, even after downgrading..

**Comment by maxtor3569** [comment]
To fix you have to replace the code in NotificationService like in the doc..
https://documentation.onesignal.com/docs/react-native-sdk-setup

**Comment by rgomezp** [comment]
Looks like the solution is to replace the import in the NotificationService.m file:

https://github.com/OneSignal/react-native-onesignal/issues/1440#issuecomment-1710521746

This will be fixed in https://github.com/OneSignal/onesignal-expo-plugin/pull/195/files

**Comment by Diaa-Ghonim** [comment]
same issue here any idea??

https://github.com/OneSignal/react-native-onesignal/issues/1440#issuecomment-1715617056
