### ISSUE TITLE
[question]: Set small icon accent color

### ISSUE THREAD

**Issue by dakshshah96** [OneSignal/onesignal-expo-plugin#183]
### How can we help?

Just like how one can specify `smallIcons` in the app config, is it also possible to define the small icon accent color in the same place? If not, that would be a great feature to implement in this SDK.

Is there any workaround to [set the accent color](https://documentation.onesignal.com/docs/customize-notification-icons#small-icon-accent-color) in the meanwhile?

### OneSignal Expo SDK version

1.3.2

### Platform

Android

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by karengrigoryan** [comment]
A custom config plugin can be used as a temporary solution, based on the [Android SDK documentation](https://documentation.onesignal.com/docs/customize-notification-icons#small-icon-accent-color).

Something along these lines:

```js
// plugins/one-signal-android-icon-accent/withOneSignalAndroidIconAccent.js

import { withStringsXml } from '@expo/config-plugins';

/**
 * A simple config plugin for One Signal that sets the push notification icon accent color on Android.
 *
 * @see {@link https://documentation.onesignal.com/docs/customize-notification-icons#set-default-small-icon-and-accent-colors} Set default Small Icon and Accent Colors
 * @see {@link https://github.com/OneSignal/onesignal-expo-plugin/issues/183} Related GitHub issue
 */
export function withOneSignalAndroidIconAccent(config, props) {
  return withStringsXml(config, (config) => {
    const colorInARGB = `FF${props.color.replace('#', '')}`;
    const strings = config.modResults.resources.string ?? [];
    const accentColorEntry = {
      $: { name: 'onesignal_notification_accent_color' },
      _: colorInARGB,
    };

    config.modResults.resources.string = [...strings, accentColorEntry];

    return config;
  });
};

export default withOneSignalAndroidIconAccent;
```

```js
// app.config.js

module.exports = {
  expo: {
    // ...
    plugins: [
      ['onesignal-expo-plugin', { //... }],
      ['./plugins/one-signal-android-icon-accent/withOneSignalAndroidIconAccent.js', { color: '#e3e3e3' }]
    ]
  },
}
```

**Comment by AdamGerthel** [comment]
@karengrigoryan this is great! Could easily create a PR for this, no?

**Comment by AdamGerthel** [comment]
Small update: The script adds the line every time it's run no matter if it already exists or not, which isn't ideal for bare workflows (i.e. when the ios/android folders exist in the project already). Might want to add a check.

**Comment by rgomezp** [comment]
@AdamGerthel I have created a PR for this. Please feel free to test it.
