### ISSUE TITLE
[feedback]: Set default small icon?

### ISSUE THREAD

**Issue by crieggalder** [OneSignal/onesignal-expo-plugin#185]
### What's on your mind?

Is it possible to set a default small icon via the plugin? Looks like I'll need to manually add icons after expo prebuild - ideally the plugin would handle this as a config option.

Relates to #183 - should also be possible to set default accent color from plugin.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by karengrigoryan** [comment]
Starting with [version 1.2.0](https://github.com/OneSignal/onesignal-expo-plugin/releases/tag/1.2.0), setting small icons for Android is supported by providing a corresponding property (`smallIcons`) in plugin [props](https://github.com/OneSignal/onesignal-expo-plugin#plugin-prop).
