### ISSUE TITLE
Update to work with react-native-onesignal@5

### ISSUE THREAD

**Issue by danbovey** [OneSignal/onesignal-expo-plugin#193]
I installed `react-native-onesignal` and `onesignal-expo-plugin` at latest versions and they're incompatible because the expo plugin is pointing at lower versions of the native module. Haven't tried an Android build but that might need updating too.

https://github.com/OneSignal/onesignal-expo-plugin/blob/495beb5857a7796f684a8f3ca93072f925fe4345/support/iosConstants.ts#L6

**Comment by yernandus** [comment]
facing the same issue. I had to manually update my pod file which is a hack

**Comment by aindong** [comment]
this issue is solved with #195 please help to merge that PR
