### ISSUE TITLE
[Bug]: [!] CocoaPods could not find compatible versions for pod "OneSignalXCFramework"

### ISSUE THREAD

**Issue by yernandus** [OneSignal/onesignal-expo-plugin#194]
### What happened?

https://github.com/OneSignal/react-native-onesignal/issues/1543 

### Steps to reproduce?

```Markdown
build expo project
```

### What did you expect to happen?

expected the build to finish successfully 

### OneSignal Expo SDK version

^5.0.0

### Platform

iOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RL-Jurica-Penjgusic** [comment]
Related to [https://github.com/OneSignal/onesignal-expo-plugin/issues/193](url)

**Comment by rgomezp** [comment]
Duplicate
