### ISSUE TITLE
[Bug]: IOS click event is not triggered.

### ISSUE THREAD

**Issue by hasanaktas** [OneSignal/onesignal-expo-plugin#198]
### What happened?

On iOS, the click event is not triggered when the app is closed. The redirectNotification function does not work at all in the logging I make.

It works when the application is in the background or open.

<img width="704" alt="image" src="https://github.com/OneSignal/onesignal-expo-plugin/assets/30148248/4485efb2-2dda-43aa-b438-ae5d4d42e0ba">

It works without any problems on Android.

### Steps to reproduce?

```Markdown
"expo": "^49.0.11"
"onesignal-expo-plugin": "^2.0.0"
"react-native-onesignal": "^5.0.0"
```

### What did you expect to happen?

I should be able to listen to this when I click on the notification with the app closed.

### OneSignal Expo SDK version

2.0.0

### Platform

iOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hello there! Apologies that this issue was missed. Please upgrade to our latest SDK and open a new issue if you are still having trouble. Thanks!
