### ISSUE TITLE
[question]: Can we completely remove the Location permission?

### ISSUE THREAD

**Issue by aldoarya** [OneSignal/onesignal-expo-plugin#215]
### How can we help?

I am building an app that only need the Push Notification feature without needing to know the location of the User at all. 
I have tried to disable the location sharing after the OneSignal initialization like below
```
OneSignal.initialize(Constants?.expoConfig?.extra?.oneSignalAppId);
OneSignal.Location.setShared(false);
```
But, it seems that the location permission is still showing in the bundled app
![image](https://github.com/OneSignal/onesignal-expo-plugin/assets/60910170/5cca9d80-6355-48bc-a017-71e7fa3d24e5)

Is there any way or plugin config that we can use to remove the needed location permission both in iOS and Android?

### OneSignal Expo SDK version

2.0.2

### Platform

iOS, Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rikur** [comment]
@aldoarya maybe `blockedPermissions` in Expo `app.json` will help?

```
"android": {
      "blockedPermissions": [
```

**Comment by emawby** [comment]
@aldoarya This issue has been resolved in our Android Native SDK so that the permission will no longer automatically be included. It will be available in our next release thank you for your patience
