### ISSUE TITLE
[question]: Confused about how to use smallIcons and largeIcons

### ISSUE THREAD

**Issue by crieggalder** [OneSignal/onesignal-expo-plugin#225]
### How can we help?

Hi - thanks for all your work on this package!

I was the requester who filed a ticket a while back for better Android icon support. Really nice to see it implemented--much appreciated!

I'm unclear about how to actually use the new `smallIcons` and `largeIcons` properties. Right now I have a folder of icons generated via [Android Asset Studio](https://romannurik.github.io/AndroidAssetStudio/icons-notification.html#source.type=clipart&source.clipart=ac_unit&source.space.trim=1&source.space.pad=0&name=ic_stat_onesignal_default) as recommended in the [OneSignal docs](https://romannurik.github.io/AndroidAssetStudio/icons-notification.html#source.type=clipart&source.clipart=ac_unit&source.space.trim=1&source.space.pad=0&name=ic_stat_onesignal_default). This folder (`res`) contains a folder for each resolution with structure `res/drawable-<resolution>dpi/ic_stat_onesignal_default.png`, where <resolution> is one of `m, h, xh, xxh, xxxh`.

How should I use this folder of icons with the `smallIcons` and `largeIcons` properties? Some added guidance in readme would help - I'd recommend a link to the generator and directions on how to use output with the properties.

Thanks again.

### OneSignal Expo SDK version

50

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rgomezp** [comment]
Expo projects get created with an assets directory. You should just be able to put them in there.

I don't think it's as complicated as on native.
