### ISSUE TITLE
[question]: I keep getting this error after i updated the expo font in the app.json plugin

### ISSUE THREAD

**Issue by princechibez** [OneSignal/onesignal-expo-plugin#233]
### How can we help?

``
"plugins": [
      "expo-router",
      "expo-font",
      {
        "fonts": [
          "./assets/fonts/Rubik-Regular.ttf"
        ]
      }
    ],
``

### OneSignal Expo SDK version

51

### Relevant log output

```Shell
PluginError: Plugin is an unexpected type: object
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mrrenaud** [comment]
This is absolutely not related to onesignal-expo-plugin, but your plugin config is not correct.
Take a look at the documentation : https://docs.expo.dev/versions/latest/sdk/font/

It should look like this : 
```javascript
"plugins": [
    "expo-router", 
    [ 
        "expo-font", 
         { 
             "fonts": [ "./assets/fonts/Rubik-Regular.ttf" ]
          }
    ]
],
```
