### ISSUE TITLE
No users/subscribers appearing in OneSignal

### ISSUE THREAD

**Issue by Ricool06** [OneSignal/onesignal-expo-plugin#24]
Hi there, love that you've created this plugin!
I can't seem to get my device subscribed to OneSignal.
I'm using expo managed workflow with the beta6 release of this plugin, I have react-native-onesignal installed, and I have followed the README and example app code for setup, but no subscribers are appearing.

The initialisation code is definitely being reached (logcat + a peppering of console.log calls show this).
I can't see OneSignal throwing any errors in logcat. It's simply failing silently. I am trying to build an APK with `expo build` to eliminate the possibility of Expo Go being the issue, and I've also tried `eas build`, but neither work.

I am using expo ^42.0.0

Let me know if I should provide more details.

**Comment by rgomezp** [comment]
Howdy,
Can you please include:

1. logs
2. environment info - device, OS, OS version, etc...
3. reproduction steps

Cheers

**Comment by Ricool06** [comment]
Right so I've got a potential solution:
- Run `eas build` with the `--clear-cache` option, it does some funny stuff with packages on the build server that helps.

For posterity, the failure truly was silent. There were no errors in the logs from the app or OneSignal. I guess the gradle package never got fetched during the build on the server.

Env info: Moto G6 Plus with Android 9

Reproduction steps: try to add this plugin and react-native-onesignal to an existing expo project, then build without the `--clear-cache` option.
I never was able to figure out why `expo build:android` experienced the silent failure too, but using EAS is viable if you can afford it.

**Comment by rgomezp** [comment]
What do you see on the All Users tab of your OneSignal app dashboard?

**Comment by Ricool06** [comment]
> What do you see on the All Users tab of your OneSignal app dashboard?

Now I see users/devices. Before, I saw nothing.

**Comment by rgomezp** [comment]
It may take a little bit of time to show. So it's possible that's what happened here. Do you have any other questions?

**Comment by opmat** [comment]
I am not currently able to run on eas build, what can be done to get this to work on expo build.
I am using expo 42.0.1, "onesignal-expo-plugin": "^1.0.0-beta7",
I am not getting any error but it fails to subscribe and I can't figure it out

**Comment by rgomezp** [comment]
@opmat ,
Can you provide more info please? What device? What are you seeing in the dashboard? Do you have logs?

**Comment by opmat** [comment]
@rgomezp

I am trying it out on Android devices (Android  9).

The thing is I already have version 1 of the App written in Ionic Cordova running. The version 2 is based on Expo React-Native, which is where I am having issues. Only those using the old version is subscribing. It is not even subscribing as I can see the devices on the User list on OneSignal.

What have I done.
1. I have installed the plugin
2. import OneSignal from "react-native-onesignal";
3. In app.json, I have this

   ```
 "plugins": [
      [
        "onesignal-expo-plugin",
        {
          "mode": "production"
        }
      ],
      [
        "expo-media-library",
        {
          "photosPermission": "Allow $(PRODUCT_NAME) to access your files/directory.",
          "savePhotosPermission": "Allow $(PRODUCT_NAME) to save files.",
          "isAccessMediaLocationEnabled": true
        }
      ]
    ], 
```
4. In my App.tsx
```
OneSignal.setLogLevel(6, 0);
  OneSignal.setAppId(Constants.manifest?.extra?.oneSignalAppId);

OneSignal.promptForPushNotificationsWithUserResponse((response) => {
    console.log("Prompt response:", response);
  });

OneSignal.addSubscriptionObserver(event => {
    console.log("OneSignal: subscription changed event:", event);
    console.log("OneSignal: subscription changed from userId:", event.from.userId);
    console.log("OneSignal: subscription changed to userId:", event.to.userId);
    console.log("OneSignal: subscription changed from pushToken:", event.from.pushToken);
    console.log("OneSignal: subscription changed to pushToken:", event.to.pushToken);
    console.log("OneSignal: subscription changed from isPushDisabled:", event.from.isPushDisabled);
    console.log("OneSignal: subscription changed to isPushDisabled:", event.to.isPushDisabled);
    console.log("OneSignal: subscription changed from isSubscribed:", event.from.isSubscribed);
    console.log("OneSignal: subscription changed to isSubscribed:", event.to.isSubscribed);
    if (event.to.isSubscribed) {
      getDeviceState();
    }
  });

  OneSignal.setNotificationOpenedHandler((jsonData) => {
    console.log('notificationOpenedCallback: ' + JSON.stringify(jsonData));
    saveThisPushNotification(jsonData);
  });

  //Method for handling notifications received while app in foreground
  OneSignal.setNotificationWillShowInForegroundHandler(
    (notificationReceivedEvent) => {
      console.log(
        "OneSignal: notification will show in foreground:",
        notificationReceivedEvent
      );
      let notification = notificationReceivedEvent.getNotification();
      saveThisPushNotification(notification);
      // Complete with null means don't show a notification.
      notificationReceivedEvent.complete(notification);
    }
  );

const [pushUserID, setPushUserID] = React.useState({});
  const getDeviceState = async () => {
    try {
      const deviceState = await OneSignal.getDeviceState();
      console.log('DEVICE STATE: ',deviceState.userId);
      // setDeviceState(deviceState);
      setPushUserID(deviceState.userId);

      if ( (deviceState.userId) && userData.userid) {
        axios
          .post(
            `${Constants.manifest.extra.apiURLProduction}savePushUUID`,
            {userid: userData.userid, uuid: deviceState.userId}
          )
          .then(function (response) {
            console.log('savePushUID: ', response)
          });
      }
      

    } catch (err) {
      console.log('savePushUID: ', err);
    }

  }

  React.useEffect(() => {
    getDeviceState();
  }, []);

```
5. I have no output in my Log

**Comment by opmat** [comment]
@rgomezp 
Any idea on what could be the issue? Or how this can be made to work with expo without having to subscribe to eas?
Thanks

**Comment by eamanola** [comment]
+1 for this issue

Android 10
expo: "~43.0.2",
onesignal-expo-plugin: "^1.0.0-beta7",
OneSignal Dashboard shows: User activity will be displayed here once you have your first user.

Any updates?

**Comment by rgomezp** [comment]
@opmat 
>It is not even subscribing as I can see the devices on the User list on OneSignal.

Hey Opmat, can you please clarify this point? You are saying you CAN see the devices on the User list?

You should be able to get a log from the [native Android Studio logcat](https://documentation.onesignal.com/docs/troubleshooting-android#with-android-studio). Getting these logs would be helpful in working towards diagnosing your issue.

@eamanola ,
Thanks for reporting. We would like to get some more information in order to help you -- in particular some logs would be helpful. See our [documentation](https://documentation.onesignal.com/docs/troubleshooting-android#with-android-studio) for more info on how to do this.

**Comment by eamanola** [comment]
@rgomezp 
Thanks for getting back.

Steps:
expo start
switch to tunnel (not sure if relevant)
run on android

app starts on phone normally

expected: One signal dashboard shows a user
actual result: 0/0 users for the appId 

[onesignal_crash_logcat.txt](https://github.com/OneSignal/onesignal-expo-plugin/files/7559895/onesignal_crash_logcat.txt)

**Comment by opmat** [comment]
> 
> 
> @opmat
> 
> > It is not even subscribing as I can see the devices on the User list on OneSignal.
> 
> Hey Opmat, can you please clarify this point? You are saying you CAN see the devices on the User list?
> 
> You should be able to get a log from the [native Android Studio logcat](https://documentation.onesignal.com/docs/troubleshooting-android#with-android-studio). Getting these logs would be helpful in working towards diagnosing your issue.
> 
> @eamanola , Thanks for reporting. We would like to get some more information in order to help you -- in particular some logs would be helpful. See our [documentation](https://documentation.onesignal.com/docs/troubleshooting-android#with-android-studio) for more info on how to do this.

I'm sorry about that. I meant I CAN'T see any users. It's not subscribing at all

**Comment by opmat** [comment]
> 
> 
> @opmat
> 
> > It is not even subscribing as I can see the devices on the User list on OneSignal.
> 
> Hey Opmat, can you please clarify this point? You are saying you CAN see the devices on the User list?
> 
> You should be able to get a log from the [native Android Studio logcat](https://documentation.onesignal.com/docs/troubleshooting-android#with-android-studio). Getting these logs would be helpful in working towards diagnosing your issue.
> 
> @eamanola , Thanks for reporting. We would like to get some more information in order to help you -- in particular some logs would be helpful. See our [documentation](https://documentation.onesignal.com/docs/troubleshooting-android#with-android-studio) for more info on how to do this.

@rgomezp 
I have gotten the logcat attached. Please Note that I changed the OneSignalAppId in the attached logcat (it is not the original)

***STEPS ( I used the app already deployed to my phone)
1. Connected my Phone to the system and enabled debugging
2. Enabled logcat
3. Opened the App

[onesignal_myfob_crash_logcat 1.txt](https://github.com/OneSignal/onesignal-expo-plugin/files/7560846/onesignal_myfob_crash_logcat.1.txt)
[onesignal_myfob_crash_logcat.txt](https://github.com/OneSignal/onesignal-expo-plugin/files/7560847/onesignal_myfob_crash_logcat.txt)

**Comment by opmat** [comment]
I have been able to get this working, all thanks to the team for the updated README.md pushed a few days ago and thanks to the EXPO team for the EAS free tier.

** For Development
I ran the following commands
1.  ``` expo prebuild ```
2. ``` expo run:android ```

** For Production
I simply ran ``` eas build ```

**Comment by yourlocal** [comment]
When I am building with `eas build -p android ` I don't get any users unless I install `react-native-onesignal`.

I tried on clean expo init.

1. installed `onesignal-expo-plugin`
2. add `"plugins": [
      [
        "onesignal-expo-plugin",
        {
          "mode": "production"
        }
      ]
    ]`
3. add `OneSignal.setAppId("MY ID");`'

did nothing until installing `react-native-onesignal`

**Comment by m1st1ck** [comment]
When I am building with `eas build -p android ` I don't get any users unless I install `react-native-onesignal`.

I tried on clean expo init.

1. installed `onesignal-expo-plugin`
2. add `"plugins": [
      [
        "onesignal-expo-plugin",
        {
          "mode": "production"
        }
      ]
    ]`
3. add `OneSignal.setAppId("MY ID");`'

did nothing until installing `react-native-onesignal`

**Comment by rgomezp** [comment]
@m1st1ck ,
Yep. That was the issue. You need to also add the `react-native-onesignal` package for RN to perform autolinking correctly.

We will attempt to resolve the issue so that adding both is not required, but for now, this is an easy, straightforward solution.

Enjoy!
