### ISSUE TITLE
Update Plugin to Catch Up with react-native-onesignal bug fixes

### ISSUE THREAD

**Issue by gitteraz** [OneSignal/onesignal-expo-plugin#31]
Hi,
I have successfully installed and tested the plugin on android but came across the issue described on react-native-onesignal repo in [1288](https://github.com/OneSignal/react-native-onesignal/issues/1288).

The proposed solutions there were:

**1 -** Revert back to react-native-onesignal@4.1.1
This is not possible using the plugin because react-native-onesignal dependency is locked at ^4.3.1 hence EAS build always tries to pick at least that version.

**2 -** Upgrade to  react-native-onesignal@4.3.3
Currently Expo uses compileSdkVersion = 30 and trying to use react-native-onesignal with a version greater than 4.3.1 throws error: 

`> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
[stderr]    > The minCompileSdk (31) specified in a
[stderr]      dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
[stderr]      is greater than this module's compileSdkVersion (android-30).
[stderr]      Dependency: androidx.work:work-runtime:2.7.1.
[stderr]      AAR metadata file: /root/.gradle/caches/transforms-3/f2e8a192284df9764ec691ee3f57b75f/transformed/work-runtime-2.7.1/META-INF/com/android/build/gradle/aar-metadata.properties.`

Please advise whats the best way to overcome this issue.

Thanks

**Comment by jkasten2** [comment]
@gitteraz `react-native-onesignal@4.3.3` should be usable for your env once the following URL is updated with the latest [`onesignal-gradle-plugin 0.14.0`](https://github.com/OneSignal/OneSignal-Gradle-Plugin/releases/tag/0.14.0).
   - https://plugins.gradle.org/m2/gradle/plugin/com/onesignal/onesignal-gradle-plugin/maven-metadata.xml

I am not sure exactly when Gradle's plugin portal will refresh the latest version list but I would expect in the next 24 hours.

**Comment by jkasten2** [comment]
The version list has been updated, closing this issue as it should be resolved now.
