### ISSUE TITLE
ld: library not found for -lPods-OneSignalNotificationServiceExtension

### ISSUE THREAD

**Issue by knilf-i-am** [OneSignal/onesignal-expo-plugin#42]
Not super familiar with Xcode, so struggling a bit with the setup of the plugin. I'm almost there, but the app fails on the build stage in Fastlane. Any suggestions on how to tackle this?

› Linking   Nuptuality/OneSignalNotificationServiceExtension » OneSignalNotificationServiceExtension

❌  ld: library not found for -lPods-OneSignalNotificationServiceExtension

❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)

▸ ** ARCHIVE FAILED **
▸ The following build commands failed:
▸ 	Ld /Users/expo/Library/Developer/Xcode/DerivedData/Nuptuality-czypadaqxhhqkcaohroovtjuwjiy/Build/Intermediates.noindex/ArchiveIntermediates/Nuptuality/IntermediateBuildFilesPath/Nuptuality.build/Release-iphoneos/OneSignalNotificationServiceExtension.build/Objects-normal/armv7/Binary/OneSignalNotificationServiceExtension normal armv7 (in target 'OneSignalNotificationServiceExtension' from project 'Nuptuality')
▸ (1 failure)
** ARCHIVE FAILED **
The following build commands failed:
	Ld /Users/expo/Library/Developer/Xcode/DerivedData/Nuptuality-czypadaqxhhqkcaohroovtjuwjiy/Build/Intermediates.noindex/ArchiveIntermediates/Nuptuality/IntermediateBuildFilesPath/Nuptuality.build/Release-iphoneos/OneSignalNotificationServiceExtension.build/Objects-normal/armv7/Binary/OneSignalNotificationServiceExtension normal armv7 (in target 'OneSignalNotificationServiceExtension' from project 'Nuptuality')
(1 failure)
Exit status: 65

**Comment by jparksecurity** [comment]
I think you can refer to https://github.com/OneSignal/react-native-onesignal/issues/838#issuecomment-665205966

Basically, we need to match the iOS target. The fix is coming. https://github.com/OneSignal/onesignal-expo-plugin/pull/41

If you can't wait, I think we can try to follow https://github.com/OneSignal/onesignal-expo-plugin/issues/40#issuecomment-1007383221

> To resolve this I had to patch the onesignal-expo-plugin to use the same iOS target as the expo sdk. (12.0 for my case).

**Comment by knilf-i-am** [comment]
Awesome thanks @jparksecurity updating the target fixed it. I'll close this out.
