### ISSUE TITLE
CFBundleShortVersionString and CFBundleVersion issue

### ISSUE THREAD

**Issue by jparksecurity** [OneSignal/onesignal-expo-plugin#48]
> WARNING ITMS-90473: "CFBundleShortVersionString Mismatch. The CFBundleShortVersionString value '1.0' of extension '*.app/PlugIns/OneSignalNotificationServiceExtension.appex' does not match the CFBundleShortVersionString value '*' of its containing iOS application '*.app'."

 >WARNING ITMS-90473: "CFBundleVersion Mismatch. The CFBundleVersion value '1' of extension '*.app/PlugIns/OneSignalNotificationServiceExtension.appex' does not match the CFBundleVersion value '*' of its containing iOS application '*.app'."

I got the warning above from the app store submission.

I control [the version](https://docs.expo.dev/versions/v44.0.0/config/app/#version) / [the build number](https://docs.expo.dev/versions/v44.0.0/config/app/#buildnumber) of my app with app.json, but when I run `expo prebuild`, I can see the version and the build number of OneSignalNotificationServiceExtension are not match to my app but just `1.0.0`.

I found a similar issue like [here](https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/63), but the solution doesn't work for our case because we use Expo managed workflow.

Can we update the plugin to match the version and the build number of OneSignalNotificationServiceExtension to the main app's ones?

Refer: https://github.com/OneSignal/onesignal-expo-plugin/blob/main/support/serviceExtensionFiles/OneSignalNotificationServiceExtension-Info.plist#L19-L22

Thanks!

**Comment by rgomezp** [comment]
Howdy,
Thanks for reporting. This is indeed an issue we will have to fix.

Thanks for your patience.

**Comment by jparksecurity** [comment]
@rgomezp Thanks for the fast reply.

I wasn't able to import the library after forked. I got the following error. I couldn't understand what was going on, so I wrote a sample code on the build files to test if I can make it work.

> No inputs were found in config file '/Users/.../Library/Caches/Yarn/v6/.tmp/a8e28abb2250e90cc5238f38548663ef.607257810e78ad1beeef52891195d2eeec2b3fa1.prepare/tsconfig.json'. Specified 'include' paths were '["./"]' and 'exclude' paths were '["**/__mocks__/*","**/__tests__/*","examples"]'.

Ref: https://github.com/OneSignal/onesignal-expo-plugin/blob/main/onesignal/withOneSignalIos.ts#L94-L99

I wanted to pass `version` and `buildNumber` from config to `xcodeProjectAddNse`, so I added them to `option`.
```
const withOneSignalNSE = (config, onesignalProps) => {
    return (0, config_plugins_1.withXcodeProject)(config, async (props) => {
        var _a;
        const options = {
            ...
            version: config.version,
            buildNumber: config.ios.buildNumber,
        };
        xcodeProjectAddNse(props.modRequest.projectName || "", options, "node_modules/onesignal-expo-plugin/build/support/serviceExtensionFiles/");
        return props;
    });
};
```

Ref: https://github.com/OneSignal/onesignal-expo-plugin/blob/main/onesignal/withOneSignalIos.ts#L165

Expo team uses `@expo/plist`, so I thought I could do the same. I parsed `OneSignalNotificationServiceExtension-Info.plist` after the file is copied. Then I updated the object before writing it back to the file.
```
const plist_1 = __importDefault(require("@expo/plist"));
...
function xcodeProjectAddNse(appName, options, sourceDir) {
    const { ..., version, buildNumber } = options;
    ...
    xcodeProject.parse(function (err) {
        ...

        const filePath = `${sourceDir}/${targetName}-Info.plist`;
        const xml = fs_1.default.readFileSync(filePath, 'utf8');
        const content = plist_1.default.parse(xml);
        content.CFBundleShortVersionString = version;
        content.CFBundleVersion = buildNumber;

        const updatedXml = plist_1.default.build(content);
        fs_1.default.writeFileSync(filePath, updatedXml);

        ...
}
```

I hope you find it helpful.

**Comment by rgomezp** [comment]
Fixed! Please upgrade to beta 10!

Enjoy
