### ISSUE TITLE
iOS entitlement/Android build script being added on every prebuild

### ISSUE THREAD

**Issue by knilf-i-am** [OneSignal/onesignal-expo-plugin#49]
`expo prebuild`

**Outcome**
<string>group.xyz.xxx.xxx.onesignal</string> is added to the iOS entitlements array even if it already exists.
buildscript is added to build.gradle even if it already exists.

Harmless, I believe, but just something I need to clean up when I bump my app versions.

**Comment by rgomezp** [comment]
Howdy,
I was able to reproduce. Thanks for reporting. We will get this fixed for the next release.

**Comment by rgomezp** [comment]
Fixed! Please upgrade to beta 10!

Enjoy

**Comment by knilf-i-am** [comment]
Appreciate it! I've pulled the upgrade and have just run the smoothest `expo prebuild` ever.

**Comment by rgomezp** [comment]
Love to hear it! @knilf-i-am
