### ISSUE TITLE
Android notifications icons in Expo setup

### ISSUE THREAD

**Issue by knilf-i-am** [OneSignal/onesignal-expo-plugin#50]
For the life of me I'm unable to figure out how to configure notification icons in an Expo setup. We previously used expo-notifications and notification icons showed up ok.

By default, Expo seems to generate `notification_icon.png` in all of the required formats when using `expo prebuild`. However, OneSignal seems to expect `ic_stat_onesignal_default.png` in all of the required formats.

Has anyone been able to get this to work?

**Comment by rgomezp** [comment]
Howdy David,
Thanks for reporting this and for your patience.

Have you tried renaming the assets manually? Of course, this is not a long-term solution but at least we will know that it works.

> Expo seems to generate notification_icon.png in all of the required formats when using expo prebuild
I don't think `expo prebuild` will generate the icons automatically. Rather, I believe it is `expo-notifications` that is responsible here. 

We will likely need to add this capability to a future version. I will go ahead and mark it as an enhancement / feature request.

Cheers

**Comment by knilf-i-am** [comment]
Confirming manually copying/renaming the notification icons to every directory under /android/app/src/main/res/ resolved the issue. Thanks for the suggestion!

**Comment by jkasten2** [comment]
@knilf-i-am Good to hear!, thanks for confirming.

**Comment by pweisensee** [comment]
Can you add a configurable property [like Expo Notifications](https://docs.expo.dev/versions/latest/sdk/notifications/#configurable-properties) that sets this up as part of the plugin and prebuild? Prebuild doesn't generate this correctly yet it seems.

**Comment by axelnormand** [comment]
I have the same issue...be awesome to be part of this config plugin to set icon
For now @knilf-i-am did you just use `fs` and copy the files and drawable folders to that ` /android/app/src/main/res/` in your own config plugin?

**Comment by kbrandwijk** [comment]
Config plugins have access the to full configuration object, so ideally, if someone has already configured their notification icon in app.json in the 'standard' Expo way, the OneSignal config plugin would pick up on that, and use those.

**Comment by axelnormand** [comment]
we do have the icon set actually (previously was using expo-notifications), would i need to name the resource ic_stat_onesignal_default?

**Comment by axelnormand** [comment]
oh sorry misunderstood..you mean the config plugin copies the expo icon asset to the right place with the right name. Nice.

**Comment by brismithers** [comment]
@metadevj are you able to workaround the issue with the `fs` trick noted above?  Will see about getting these suggestions in so it is more seamless.
