### ISSUE TITLE
Stuck on splash screen with TestFlight 

### ISSUE THREAD

**Issue by dynamiccarrots** [OneSignal/onesignal-expo-plugin#51]
I am in the process of testing One Signal with Expo so I have a fresh Expo install that runs fine when deployed to an iPhone using TestFlight. I used the `expo init` command to create this and complied the app using Expos servers.

However, as soon as I add this plugin and compile the app in the same way, TestFlight just hangs on the splash screen, I have even installed Sentry to see if I can get any errors from it but it's not even getting to that point. 

Here are all the files from my app that I have changed when adding this plugin, any help would be much appreciated here. 

app.json
```{
  "expo": {
    "name": "notificationtest",
    "slug": "notificationtest",
    "version": "1.0.8",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "com.dynamiccarrots.testapp",
      "buildNumber": "1.0.8"
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#FFFFFF"
      }
    },
    "web": {
      "favicon": "./assets/favicon.png"
    },
    "hooks": {
      "postPublish": [
        {
          "file": "sentry-expo/upload-sourcemaps",
          "config": {
            "url": "{REMOVED FOR HERE}",
            "organization": "appdev",
            "project": "notificationtest",
            "authToken": "{REMOVED FOR HERE}"
          }
        }
      ]
    },
    "extra": {
      "oneSignalAppId": "c21f7175-4c13-4a79-8f48-67cf2736e174" // not the real ID for here
    },
    "plugins": [
      [
        "onesignal-expo-plugin",
        {
          "mode": "development",
          "devTeam": "{REMOVED FOR HERE}"
        }
      ]
    ]
  }
}
```

App.js

```
import { StatusBar } from 'expo-status-bar';
import { StyleSheet, Text, View } from 'react-native';
import OneSignal from 'react-native-onesignal';
import Constants from "expo-constants";

Sentry.init({
  dsn: 'https://cfc1ebd0e9934b12a931b71c4c606a33@sentry.stechga.co.uk/36',
  enableInExpoDevelopment: true,
  debug: true, // If `true`, Sentry will try to print out useful debugging information if something goes wrong with sending the event. Set it to `false` in production
});

OneSignal.setAppId(Constants.manifest.extra.oneSignalAppId);



export default function App() {
  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

package.json

```
{
  "scripts": {
    "start": "react-native start",
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@sentry/react-native": "^3.2.13",
    "expo": "~44.0.0",
    "expo-application": "^4.0.1",
    "expo-constants": "^13.0.1",
    "expo-device": "^4.1.0",
    "expo-splash-screen": "~0.14.1",
    "expo-status-bar": "~1.2.0",
    "expo-updates": "^0.11.5",
    "onesignal-expo-plugin": "^1.0.0-beta9",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-onesignal": "^4.3.5",
    "react-native-web": "0.17.1",
    "sentry-expo": "^4.0.3"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9"
  },
  "private": true,
  "name": "app",
  "version": "1.0.0"
}
```

**Comment by knilf-i-am** [comment]
Can you check the device logs in Xcode? Windows > Devices and simulators > Your device > Open console > Start. Just start your app and pause the console capture. Sort by process to find your app and you should find the error message that's causing your app to hang.

**Comment by dynamiccarrots** [comment]
> Can you check the device logs in Xcode? Windows > Devices and simulators > Your device > Open console > Start. Just start your app and pause the console capture. Sort by process to find your app and you should find the error message that's causing your app to hang.

What should I be looking for in here, I have searched for my apps name and TestFlight but can't find anything meaningful :/

**Comment by dynamiccarrots** [comment]
I have found some output from TestFlight, but struggling to work out what is an issue and what is normal.

There are a few errors here 

`error	12:30:57.411484+0400	accountsd	Unentitled access by client 'TestFlight' (selector: <private>)
error	12:30:55.354748+0400	TestFlight	Task <2E5964E7-967D-464F-A0AD-CCD117AF6F4D>.<6> finished with error [-1001] Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={_kCFStreamErrorCodeKey=-2102, NSUnderlyingError=0x2813c50e0 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, _NSURLErrorFailingURLSessionTaskErrorKey=<private>, _NSURLErrorRelatedURLSessionTaskErrorKey=<private>, NSLocalizedDescription=The request timed out., NSErrorFailingURLStringKey=<private>, NSErrorFailingURLKey=<private>, _kCFStreamErrorDomainKey=4}
error	12:30:55.354780+0400	TestFlight	Task <43BC3CCF-097B-4154-AB11-09385074D9FC>.<17> finished with error [-1001] Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={_kCFStreamErrorCodeKey=-2102, NSUnderlyingError=0x2813c4c30 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, _NSURLErrorFailingURLSessionTaskErrorKey=<private>, _NSURLErrorRelatedURLSessionTaskErrorKey=<private>, NSLocalizedDescription=The request timed out., NSErrorFailingURLStringKey=<private>, NSErrorFailingURLKey=<private>, _kCFStreamErrorDomainKey=4}
error	12:30:57.375593+0400	TestFlight	Skipping delegate callback, splitViewController:collapseSecondaryViewController:ontoPrimaryViewController:. Unsupported for UISplitViewController style DoubleColumn
error	12:30:57.411607+0400	TestFlight	"Error returned from daemon: Error Domain=com.apple.accounts Code=9"
` 

`default	12:33:21.008279+0400	TestFlight	tcp_timers [C28.1:3] retransmit seq=3796984124 3
default	12:33:22.882719+0400	TestFlight	tcp_timers [C17.1:3] retransmit seq=2774458027 6
default	12:33:25.603764+0400	TestFlight	tcp_timers [C28.1:3] retransmit seq=3796984124 4
default	12:33:26.161463+0400	TestFlight	Evaluating dispatch of UIEvent: 0x2828518c0; type: 0; subtype: 0; backing type: 11; shouldSend: 1; ignoreInteractionEvents: 0, systemGestureStateChange: 0
default	12:33:26.161547+0400	TestFlight	Sending UIEvent type: 0; subtype: 0; to windows: 1
default	12:33:26.161631+0400	TestFlight	Sending UIEvent type: 0; subtype: 0; to window: <UIWindow: 0x10340b7a0>; contextId: 0x5C04DD54
default	12:33:26.168365+0400	TestFlight	Evaluating dispatch of UIEvent: 0x2828518c0; type: 0; subtype: 0; backing type: 11; shouldSend: 0; ignoreInteractionEvents: 0, systemGestureStateChange: 0
default	12:33:26.192195+0400	TestFlight	Evaluating dispatch of UIEvent: 0x2828518c0; type: 0; subtype: 0; backing type: 11; shouldSend: 0; ignoreInteractionEvents: 0, systemGestureStateChange: 1
default	12:33:26.224508+0400	TestFlight	Evaluating dispatch of UIEvent: 0x2828518c0; type: 0; subtype: 0; backing type: 11; shouldSend: 1; ignoreInteractionEvents: 0, systemGestureStateChange: 0
default	12:33:26.224586+0400	TestFlight	Sending UIEvent type: 0; subtype: 0; to windows: 1
default	12:33:26.224937+0400	TestFlight	Sending UIEvent type: 0; subtype: 0; to window: <UIWindow: 0x10340b7a0>; contextId: 0x5C04DD54
default	12:33:26.320022+0400	TestFlight	<private>: Will add backgroundTask with taskName: <private>, expirationHandler: <__NSMallocBlock__: 0x28131b450>
default	12:33:26.320045+0400	TestFlight	<private>: Created background task <private>. Assertion will be assigned soon
default	12:33:26.320091+0400	TestFlight	<private>: Creating new assertion since assertion is nil
default	12:33:26.320115+0400	TestFlight	<private>: Created new assertion <BKSProcessAssertion: 0x283e18870>
default	12:33:26.329586+0400	TestFlight	SSVTelephonyController: Process TestFlight is missing required telephony entitlement. Skipping instantiation of CoreTelephonyClient.
default	12:33:26.329647+0400	TestFlight	sceneOfRecord: sceneID: sceneID:com.apple.TestFlight-default  persistentID: 37D71408-8F1B-46E8-BCFC-1DC4C9215B90
default	12:33:26.330316+0400	TestFlight	<private>: Ending background task with UIBackgroundTaskIdentifier: 118
default	12:33:26.330383+0400	TestFlight	<private>: Will add backgroundTask with taskName: <private>, expirationHandler: <__NSMallocBlock__: 0x28132a9d0>
default	12:33:26.330473+0400	TestFlight	<private>: Created background task <private>. Assertion will be assigned soon
default	12:33:26.330497+0400	TestFlight	<private>: Ending task with identifier 118 and description: <private>, _expireHandler: <__NSMallocBlock__: 0x28131b450>
default	12:33:26.330610+0400	TestFlight	<private>: Decrementing reference count for assertion used by background task with identifier 118: <private>
default	12:33:26.330631+0400	TestFlight	<private>: Will invalidate assertion: <BKSProcessAssertion: 0x283e18870> for task identifier: 118
default	12:33:26.330652+0400	TestFlight	<private>: Creating new assertion since assertion is nil
default	12:33:26.330703+0400	TestFlight	<private>: Created new assertion <BKSProcessAssertion: 0x283e7be80>
default	12:33:26.330925+0400	TestFlight	<private>: Will add backgroundTask with taskName: <private>, expirationHandler: <__NSMallocBlock__: 0x28131a580>
default	12:33:26.330948+0400	TestFlight	<private>: Created background task <private>. Assertion will be assigned soon
default	12:33:26.331152+0400	TestFlight	SSVTelephonyController: Process TestFlight is missing required telephony entitlement. Skipping instantiation of CoreTelephonyClient.
default	12:33:26.331538+0400	TestFlight	<private>: Reusing assertion <BKSProcessAssertion: 0x283e7be80>
default	12:33:26.331711+0400	TestFlight	[SSMetricsController] Flushing events
default	12:33:26.331754+0400	TestFlight	sceneOfRecord: sceneID: sceneID:com.apple.TestFlight-default  persistentID: 37D71408-8F1B-46E8-BCFC-1DC4C9215B90
default	12:33:26.331792+0400	TestFlight	Deactivation reason added: 5; deactivation reasons: 0 -> 32; animating application lifecycle event: 1
default	12:33:26.331931+0400	TestFlight	Deactivation reason added: 12; deactivation reasons: 32 -> 4128; animating application lifecycle event: 1
default	12:33:26.332036+0400	TestFlight	<private>: Ending background task with UIBackgroundTaskIdentifier: 119
default	12:33:26.332097+0400	TestFlight	<private>: Ending task with identifier 119 and description: <private>, _expireHandler: <__NSMallocBlock__: 0x28136f7e0>
default	12:33:26.332165+0400	TestFlight	<private>: Decrementing reference count for assertion used by background task with identifier 119: <private>
default	12:33:26.332375+0400	TestFlight	<private>: Ending background task with UIBackgroundTaskIdentifier: 120
default	12:33:26.332420+0400	TestFlight	<private>: Ending task with identifier 120 and description: <private>, _expireHandler: <__NSMallocBlock__: 0x28136ca50>
default	12:33:26.332442+0400	TestFlight	<private>: Decrementing reference count for assertion used by background task with identifier 120: <private>
default	12:33:26.332463+0400	TestFlight	<private>: Will invalidate assertion: <BKSProcessAssertion: 0x283e7be80> for task identifier: 120
default	12:33:26.603599+0400	TestFlight	tcp_timers [C14.1:3] retransmit seq=2189863482 10
default	12:33:27.085678+0400	TestFlight	sceneOfRecord: sceneID: sceneID:com.apple.TestFlight-default  persistentID: 37D71408-8F1B-46E8-BCFC-1DC4C9215B90
default	12:33:27.085705+0400	TestFlight	Deactivation reason added: 11; deactivation reasons: 4128 -> 6176; animating application lifecycle event: 0
default	12:33:27.085731+0400	TestFlight	<private>: Will add backgroundTask with taskName: <private>, expirationHandler: (null)
default	12:33:27.085786+0400	TestFlight	<private>: Created background task <private>. Assertion will be assigned soon
default	12:33:27.085823+0400	TestFlight	<private>: Creating new assertion since assertion is nil
default	12:33:27.085851+0400	TestFlight	<private>: Created new assertion <BKSProcessAssertion: 0x283e76670>
default	12:33:27.086148+0400	TestFlight	<private>: Will add backgroundTask with taskName: <private>, expirationHandler: <__NSMallocBlock__: 0x28130c900>
default	12:33:27.086174+0400	TestFlight	Removing presenter C3EFC096-2439-4574-BC1B-7CFFF5A40AC5
default	12:33:27.086222+0400	TestFlight	<private>: Created background task <private>. Assertion will be assigned soon
default	12:33:27.086316+0400	TestFlight	<private>: Reusing assertion <BKSProcessAssertion: 0x283e76670>
default	12:33:27.086349+0400	TestFlight	<private>: Ending background task with UIBackgroundTaskIdentifier: 122
default	12:33:27.086385+0400	TestFlight	<private>: Ending task with identifier 122 and description: <private>, _expireHandler: <__NSMallocBlock__: 0x281332ee0>
default	12:33:27.086410+0400	TestFlight	<private>: Decrementing reference count for assertion used by background task with identifier 122: <private>
default	12:33:27.086435+0400	TestFlight	<private>: Will add backgroundTask with taskName: <private>, expirationHandler: <__NSMallocBlock__: 0x281332ee0>
default	12:33:27.086460+0400	TestFlight	<private>: Created background task <private>. Assertion will be assigned soon
default	12:33:27.086483+0400	TestFlight	<private>: Reusing assertion <BKSProcessAssertion: 0x283e76670>
default	12:33:27.086507+0400	TestFlight	<private>: Ending background task with UIBackgroundTaskIdentifier: 123
default	12:33:27.086530+0400	TestFlight	<private>: Ending task with identifier 123 and description: <private>, _expireHandler: <__NSMallocBlock__: 0x28130f2a0>
default	12:33:27.086554+0400	TestFlight	<private>: Decrementing reference count for assertion used by background task with identifier 123: <private>
default	12:33:27.086672+0400	TestFlight	<private>: Will add backgroundTask with taskName: <private>, expirationHandler: <__NSMallocBlock__: 0x28131ae50>
default	12:33:27.086695+0400	TestFlight	<private>: Created background task <private>. Assertion will be assigned soon
default	12:33:27.086720+0400	TestFlight	<private>: Reusing assertion <BKSProcessAssertion: 0x283e76670>
default	12:33:27.086744+0400	TestFlight	<private>: Ending background task with UIBackgroundTaskIdentifier: 124
default	12:33:27.086767+0400	TestFlight	<private>: Ending task with identifier 124 and description: <private>, _expireHandler: <__NSMallocBlock__: 0x28130f2a0>
default	12:33:27.086838+0400	TestFlight	<private>: Decrementing reference count for assertion used by background task with identifier 124: <private>
default	12:33:27.086860+0400	TestFlight	<private>: Will add backgroundTask with taskName: <private>, expirationHandler: <__NSMallocBlock__: 0x28130f2a0>
default	12:33:27.086883+0400	TestFlight	<private>: Created background task <private>. Assertion will be assigned soon
default	12:33:27.086930+0400	TestFlight	<private>: Reusing assertion <BKSProcessAssertion: 0x283e76670>
default	12:33:27.086954+0400	TestFlight	<private>: Ending background task with UIBackgroundTaskIdentifier: 125
default	12:33:27.087461+0400	TestFlight	<private>: Ending task with identifier 125 and description: <private>, _expireHandler: <__NSMallocBlock__: 0x28136a6d0>
default	12:33:27.087508+0400	TestFlight	<private>: Decrementing reference count for assertion used by background task with identifier 125: <private>
default	12:33:27.089205+0400	TestFlight	Deactivation reason removed: 5; deactivation reasons: 6176 -> 6144; animating application lifecycle event: 0
default	12:33:27.089277+0400	TestFlight	<private>: Will add backgroundTask with taskName: <private>, expirationHandler: <__NSMallocBlock__: 0x281331a40>
default	12:33:27.089370+0400	TestFlight	<private>: Created background task <private>. Assertion will be assigned soon
default	12:33:27.089957+0400	TestFlight	<private>: Reusing assertion <BKSProcessAssertion: 0x283e76670>
default	12:33:27.089982+0400	TestFlight	Performing snapshot request 0x281332970 (type 1)
default	12:33:27.163889+0400	TestFlight	Snapshot request 0x281332970 complete
default	12:33:27.172935+0400	TestFlight	Performing snapshot request 0x28131fc60 (type 1)
default	12:33:27.208276+0400	TestFlight	Snapshot request 0x28131fc60 complete
default	12:33:27.208300+0400	TestFlight	<private>: Ending background task with UIBackgroundTaskIdentifier: 126
default	12:33:27.208323+0400	TestFlight	<private>: Ending task with identifier 126 and description: <private>, _expireHandler: <__NSMallocBlock__: 0x281331a40>
default	12:33:27.208349+0400	TestFlight	<private>: Decrementing reference count for assertion used by background task with identifier 126: <private>
default	12:33:27.228058+0400	TestFlight	[0x28365da40] [keyboardFocus] Disabling event deferring records requested: adding recreation reason: detachedContext; for reason: _UIEventDeferringManager: 0x28365da40: disabling keyboardFocus: context detached for window: 0x10340b7a0; contextID: 0x5C04DD54
default	12:33:27.247317+0400	TestFlight	<private>: Ending background task with UIBackgroundTaskIdentifier: 121
default	12:33:27.247361+0400	TestFlight	<private>: Ending task with identifier 121 and description: <private>, _expireHandler: (null)
default	12:33:27.247392+0400	TestFlight	<private>: Decrementing reference count for assertion used by background task with identifier 121: <private>
default	12:33:27.247422+0400	TestFlight	<private>: Will invalidate assertion: <BKSProcessAssertion: 0x283e76670> for task identifier: 121
default	12:33:27.247736+0400	TestFlight	sceneOfRecord: sceneID: sceneID:com.apple.TestFlight-default  persistentID: 37D71408-8F1B-46E8-BCFC-1DC4C9215B90
`

**Comment by dynamiccarrots** [comment]
I seem to have found this in the console 

`Invariant Violation: Native module cannot be null.`

Very confused as I do not have this issue in the simulator :/

**Comment by rgomezp** [comment]
Closing since this is addressed in [duplicate discussion](https://github.com/OneSignal/onesignal-expo-plugin/discussions/45#discussion-3804600)

**Comment by rgomezp** [comment]
@frossetto ,
Not a problem. If you remove the OneSignal integration altogether, does the issue occur?

**Comment by rgomezp** [comment]
Closing due to no response.
