### ISSUE TITLE
Plugin is an unexpected type: object

### ISSUE THREAD

**Issue by kisonay** [OneSignal/onesignal-expo-plugin#54]
Trying to follow the directions and receive the following error when modifying the plugin array:

```
"plugins": [
      "onesignal-expo-plugin",
      {
        "mode": "development",
      }
    ]
```
Error:

```
Plugin is an unexpected type: object
```

If I remove the object, then I receive the following error:

```
Missing required "mode" key in your app.json or app.config.js file for "onesignal-expo-plugin".
```

Package dependencies:

```
"dependencies": {
    "expo": "~44.0.0",
    "expo-status-bar": "~1.2.0",
    "onesignal-expo-plugin": "^1.0.0-beta10",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-web": "0.17.1",
    "expo-splash-screen": "~0.14.1"
  },
```

**Comment by rgomezp** [comment]
Howdy,
You're missing an extra set of brackets. Check the README again for reference.

Enjoy!

**Comment by kisonay** [comment]
Doh, now I feel foolish. Cant tell you hoe many times I compared it to the docs...

**Comment by m5atib** [comment]
This message often appears when there is an error in the `app.json` file

**Comment by DeliveranceTechSolutions** [comment]
I second @m5atib my problem was the app.json with something random in it.

**Comment by nazirahmad7340** [comment]
"plugins": [
    [
          "onesignal-expo-plugin",
          {
            "mode": "development",
          }
    ]
    ]
    
    you have a missing []
    This is the correct syntax

**Comment by devnshankar** [comment]
```  "plugins": [[
      "expo-router",
      "expo-image-picker",
      {
        "photosPermission": "The app accesses your photos to let you share them with your friends."
      }]
      ```

## The error when double square  brackets are imlpimented as guided in the docs
```
AssertionError [ERR_ASSERTION]: Wrong number of arguments provided for static config plugin, expected either 1 or 2, got 3
```
---
I've been scratching my head since 5 minutes still no solution.

**Comment by SaeedSoheili** [comment]
> ```
> "plugins": [[
>     "expo-router",
>     "expo-image-picker",
>     {
>       "photosPermission": "The app accesses your photos to let you share them with your friends."
>     }]]
> ```
> 
> ## The error when double square brackets are imlpimented as guided in the docs
> ```
> AssertionError [ERR_ASSERTION]: Wrong number of arguments provided for static config plugin, expected either 1 or 2, got 3
> ```
> 
> I've been scratching my head since 5 minutes still no solution.

i think correct solution is like:

```
    "plugins": [
      "@react-native-google-signin/google-signin",
      [
        "expo-build-properties",
        {
          "android": {
            "usesCleartextTraffic": true
          }
        }
      ]
    ],
```

**Comment by princechibez** [comment]
``
"plugins": [
      "expo-router",
      "expo-font",
      {
        "fonts": [
          "./assets/fonts/Rubik-Regular.ttf"
        ]
      }
    ],
``

I tried adding expo font to the plugin and it keeps returning an error
`` PluginError: Plugin is an unexpected type: object ``

**Comment by hasanzu514** [comment]
> `"plugins": [ "expo-router", "expo-font", { "fonts": [ "./assets/fonts/Rubik-Regular.ttf" ] } ],`
> 
> I tried adding expo font to the plugin and it keeps returning an error `PluginError: Plugin is an unexpected type: object`

I had the same error but looking at the above replies I did the following (wrapped all the expo font part in brakcets):
`"plugins": [ "expo-router", ["expo-font", { "fonts": [ "./assets/fonts/Rubik-Regular.ttf" ] } ]]`

**Comment by Birhane-G** [comment]
Each item in the plugins array must represent only one plugin  

```
"plugins": [
      "expo-router",
      "expo-asset",
      [
        "expo-location",
        {
          "locationAlwaysAndWhenInUsePermission": "Allow GiftCraft to use your location to show relevant content."
        }
      ],
      [
        "expo-image-picker",
        {
          "photosPermission": "The app needs access to your photos to let you choose images for customization."
        }
      ] 
    ],
```
