### ISSUE TITLE
No push notification on iOS

### ISSUE THREAD

**Issue by jparksecurity** [OneSignal/onesignal-expo-plugin#56]
The app push notification doesn't work on iOS whereas it works on Android.

I'm not even sure what to share here to help you debug this. Please let me know what information you'd like to have.

The notification stops working when one signal is added, and it works just fine when one signal is removed.

**Comment by jkasten2** [comment]
@jparksecurity 

> The notification stops working when one signal is added, and it works just fine when one signal is removed.

What notification library are you using that stops working when adding OneSignal?

Is the device registering with OneSignal if you go to the "All Users" page on the dashboard?

Please let us know the exact versions of OneSignal and other notification libraries you are using as well as the version of React Native.

**Comment by jparksecurity** [comment]
@jkasten2 
Hi, I'm using expo notification, and it still works on Android.

I don't register a device to OneSingnal and don't send a notification through OneSignal. I collect only a user's email for OneSignal.

```
"onesignal-expo-plugin": "^1.0.0-beta9",
"react-native-onesignal": "^4.3.3",
"react-native": "https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz",
"expo": "^42.0.0",
"expo-notifications": "~0.12.3",
```

If it's not feasible to work on, feel free to close it.

**Comment by rgomezp** [comment]
Howdy @jparksecurity ,
Sorry for the delay. Can you please update on whether or not you were able to resolve this issue? If not, we're happy to leave this open until we resolve the issue.
