### ISSUE TITLE
Keychain on iOS

### ISSUE THREAD

**Issue by jparksecurity** [OneSignal/onesignal-expo-plugin#57]
iOS keychain doesn't work after adding one signal. By any chance, does anyone know how to fix it?

| Before | After |
| ------ | ------|
|![IMG_0622](https://user-images.githubusercontent.com/14362029/152264978-4dd5d48b-9c6b-453e-9bb4-0bcbca8da354.PNG)| ![IMG_0621](https://user-images.githubusercontent.com/14362029/152264998-c93d7e0b-9077-4ae9-9e53-221acaf2e82e.PNG)|

**Comment by jkasten2** [comment]
@jparksecurity Can you provide more details on what does and does not work with Keychain after adding OneSignal?
Please share the exact versions of these libraries and the version of react native you are using.

Also is this an issue with only iOS, or Android too?

If possible please provide exact steps to reproduce from a new project, or share a project reproducing the issue.

**Comment by jparksecurity** [comment]
I don't use Android, so I don't know if Android provides a similar feature.

The problem with Keychain is it doesn't suggest my id and password anymore like screenshots. It seems Keychain doesn't associate my app with my domain anymore.

e.g., if I sign in to Facebook through a mobile browser and allow iOS to remember my id and password, the Keychain should suggest my id and password when I try to sign in on the Facebook mobile application because the Keychain associates the app to its domain(facebook.com).

libraries versions:
```
"onesignal-expo-plugin": "^1.0.0-beta9",
"react-native-onesignal": "^4.3.3",
"react-native": "https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz",
"expo": "^42.0.0",
```

I believe in order to produce this issue, 
1. Build a basic Expo app with sign-in screen
2. set up associated domains on iOS https://developer.apple.com/documentation/xcode/supporting-associated-domains
3. build the IPA file and see if Keychain works for the domain and the app associated with the domain
4. Add onesignal
5. see if Keychain still works.

Sorry, I can't create a new project reproducing the same issue because it requires an Apple developer account which I don't have.

If it's not feasible to work on, feel free to close it.
