### ISSUE TITLE
error: No profiles for 'x.x.OneSignalNotificationServiceExtension' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'x.x.OneSignalNotificationServiceExtension'

### ISSUE THREAD

**Issue by gobooc-geo** [OneSignal/onesignal-expo-plugin#73]
Hi,

I'm having an issue with the building process using `react-native expo` and [EAS](https://docs.expo.dev/build/introduction/) for the IOS build

I'm using this *Expo project template:*
![image](https://user-images.githubusercontent.com/103096614/161906793-d69b7085-67de-421b-8723-e9e2d67e50bc.png)

I follow this documentation to Generate an iOS Push Certificate:
https://documentation.onesignal.com/docs/generate-an-ios-push-certificate

`Run fastlane` build process error: 
![image](https://user-images.githubusercontent.com/103096614/161906080-eeb78e56-b401-4922-ae92-3fd3a482f0da.png)
![image](https://user-images.githubusercontent.com/103096614/161905970-a0904ee2-ca4b-49eb-b49d-d7fb7ba669b7.png)
 
I tried using the `EAS` automatic creation of the `provisioning profile` and manually creating the `provisioning profile` with the name `com.gobooc.app.OneSignalNotificationServiceExtension` but it doesn't work.

**Comment by rgomezp** [comment]
Howdy,
The push certificate is completely separate from your provisioning profiles / entitlements.

Check your Apple Developer dashboard to confirm that you have the necessary profiles.

**Comment by gobooc-geo** [comment]
> Collaborator

Hi, @rgomezp thanks for your response,

I contacted OneSignal support and they provided me with this documentation specific for my setup 
https://github.com/OneSignal/onesignal-expo-plugin/blob/main/IOS_CREDENTIALS_EAS.md#4-add-the-profiles-to-your-credentialsjson-file
