### ISSUE TITLE
[Bug]: Bundle identifier of extension doesn't update when prebuild again

### ISSUE THREAD

**Issue by mhammerc** [OneSignal/onesignal-expo-plugin#87]
### What happened?

Hello!

First, thanks for the package. It makes development so much easier!

My `app.config.js` have a variable iOS bundle identifier: according to the current environment, it will generate either a production or a staging app.

On the first generation of the `ios` folder, everything works as expected:
- My app bundle identifier: `com.myapp.app1`
- OneSignal bundle identifier: `com.myapp.app1.OneSignalNotificationServiceExtension`

Then, I update my native files by running again `expo prebuild` using a different environment (without `--clean`).
- My app new bundle identifier: `com.myapp.app2`
- OneSignal bundle identifier: `com.myapp.app1.OneSignalNotificationServiceExtension`

While doing the second generation, `onesignal-expo-plugin` output the following:
```
onesignal-expo-plugin: OneSignal dependencies already added to build.gradle. Skipping...
onesignal-expo-plugin: OneSignalNotificationServiceExtension target already added to Podfile. Skipping..
onesignal-expo-plugin: OneSignalNotificationServiceExtension already exists in project. Skipping...
```

As you can see, the OneSignal extension isn't updated to the new bundle identifier.

I may be using `expo prebuild` wrong? I do the following:

- `expo prebuild` -> fallback to DEV environment
- `env APP_ENV=STAGING expo prebuild` -> staging configuration (with staging bundle identifier)
- `env APP_ENV=PRODUCTION expo prebuild` -> production configuration

The solution to this is simply to remove `ios` and `android` folders before each `expo prebuild`. Or using `expo prebuild --clean`.

### Steps to reproduce?

```Markdown
1. Create an empty expo project
2. add OneSignal Expo with a basic configuration and the expo plugin.
3. Set a first bundle identifier in app.json
4. run `expo prebuild`
5. Set a new bundle indentifier
6. run `expo prebuild` again
7. Note that the app bundle identifier is correct but the OneSignalExtension bundle identifier is wrong
```

### What did you expect to happen?

The bundle identifier should update on `expo prebuild`

### OneSignal Expo SDK version

`"react-native-onesignal": "4.3.7"`
`"onesignal-expo-plugin": "1.0.1"`

### Platform

iOS

### Relevant log output

```Shell
env APP_ENV=STAGING yarn expo prebuild
yarn run v1.22.18
$ expo prebuild
✔ Created native projects | /android, /ios **already created** | gitignore already synced
✔ Updated package.json and added index.js entry point for iOS and Android
🧶 Using Yarn to install packages. Pass --npm to use npm instead.
✔ Installed JavaScript dependencies 1606ms
        onesignal-expo-plugin: OneSignal dependencies already added to build.gradle. Skipping...
        onesignal-expo-plugin: OneSignalNotificationServiceExtension target already added to Podfile. Skipping..
        onesignal-expo-plugin: **OneSignalNotificationServiceExtension already exists in project. Skipping...**
✔ Config synced
✨  Done in 5.24s.
```

(added `**` around interesting parts)
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rgomezp** [comment]
Howdy @mhammerc ,
That would be expected behavior. The plugin doesn't check for changes in bundle id so it would be best to run --clean every time. Are there any drawbacks for you in doing that? If so, we would need to add logic in the plugin to detect the change automatically but that would be an enhancement / feature request.

**Comment by mhammerc** [comment]
Hello @rgomezp!

There is no real drawbacks in doing `--clean` every time.

Expo properly does update the bundle id without doing `--clean`. If the onesignal plugin wants feature parity with Expo, it should do the same I think.

Thank you for your plugins, it help us a lot!

**Comment by rgomezp** [comment]
@mhammerc 
Thank you for your input. I'm glad to hear other than that the plugin is useful to you. Please let us know if there is anything else we could improve.

**Comment by mhammerc** [comment]
> @mhammerc Thank you for your input. I'm glad to hear other than that the plugin is useful to you. Please let us know if there is anything else we could improve.

Hello again @rgomezp.

This documentation: https://github.com/OneSignal/onesignal-expo-plugin/blob/main/IOS_CREDENTIALS_EAS.md#capabilities should have been fixed by eas-cli by this PR: https://github.com/expo/eas-cli/pull/1078.

Their fix works on my end: `Multiple capabilities` + `Managed credentials` works reliably for me. (so far)

**Comment by rgomezp** [comment]
@mhammerc ,
Thanks again. So presumably, it wasn't working for you before? I'd like to get enough signal from people that it's working now.

**Comment by rgomezp** [comment]
Can we close this issue?

**Comment by mhammerc** [comment]
> @mhammerc , Thanks again. So presumably, it wasn't working for you before? I'd like to get enough signal from people that it's working now.

Yes, it wasn't working for me before. Here is the issue I opened before they committed the fix. All my details are in this issue! (I actually opened the issue on eas-cli before I saw you had this "bug" documented.)
https://github.com/expo/eas-cli/issues/1065



> Can we close this issue?

Yes we can! Sorry for answering here.

**Comment by rgomezp** [comment]
@mhammerc 
One thing that is interesting is that we haven't merged the [SDK-side fix](https://github.com/OneSignal/onesignal-expo-plugin/pull/89/files) and it still worked for you. That's great! But just want to see whether you included these changes somehow in your working build.

**Comment by mhammerc** [comment]
> @mhammerc One thing that is interesting is that we haven't merged the [SDK-side fix](https://github.com/OneSignal/onesignal-expo-plugin/pull/89/files) and it still worked for you. That's great! But just want to see whether you included these changes somehow in your working build.

Oh! I didn't realized there is a SDK-side fix. I just made a clean install and launched a new build to be 100% sure, it succeeds. No entitlements conflict as before. I don't know the internals of expo and expo plugins, so I may miss something.

I am using `onesignal-expo-plugin` `1.0.1`
