### ISSUE TITLE
[question]: How does this work with VOIP Push Notifications?

### ISSUE THREAD

**Issue by newme616** [OneSignal/onesignal-expo-plugin#96]
### How can we help?

I am actually a bit overwhelmed on how to setup voip notifications for RN Native with EAS? I previously worked with expo notifications, but switched to one signal. 

Can I use the Expo Plugin also for voip or are there addtional steps required?

Thank you in advance!

### OneSignal Expo SDK version

1.0.2

### Platform

iOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@newme616 This plugin nor does the `react-native-onesignal` SDK and the `OneSignal-iOS-SDK` under the hood has support for VoIP notifications.

The OneSignal backend does support VoIP, but you must use Apple's API directly (or use another plugin) to register for a VoIP token and make a REST API call to add it to your app. More details here:
https://documentation.onesignal.com/docs/voip-notifications

Let us know the features you need from VoIP iOS push, we can consider adding it in the future.

**Comment by newme616** [comment]
@jkasten2 thank you for the quick reply. I will try to do it with this library: https://github.com/react-native-webrtc/react-native-voip-push-notification and this https://github.com/react-native-webrtc/react-native-callkeep. 

It would be fantastic if one signal SDK would also support pushkit and callkeep. Also the iOS 13 requirements are not entirely clear to me.

We are currently working on a voice app. We use agora for connecting, but that only works if both users are in-app, that's why we need voip push notifications.

**Comment by whoiswentz** [comment]
> @jkasten2 thank you for the quick reply. I will try to do it with this library: https://github.com/react-native-webrtc/react-native-voip-push-notification and this https://github.com/react-native-webrtc/react-native-callkeep.
> 
> It would be fantastic if one signal SDK would also support pushkit and callkeep. Also the iOS 13 requirements are not entirely clear to me.
> 
> We are currently working on a voice app. We use agora for connecting, but that only works if both users are in-app, that's why we need voip push notifications.

You was able to run these libraries using expo?

**Comment by jason-shen** [comment]
this does work with react-native-voip-push i had it working few years ago with some mode to the code
